// Code generated by oagen. DO NOT EDIT.

package workos_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/workos/workos-go/v9"
)

func TestAgents_UpdateAttempts(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/agents/claims/attempts", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/claim_view_response.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Agents().UpdateAttempts(context.Background(), &workos.AgentsUpdateAttemptsParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "agent_reg_01EHWNCE74X7JSDV0X3SZ3KJNY", result.ID)
	require.Equal(t, "BCDF-GHJK", result.UserCode)
}

func TestAgents_CreateValidate(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/agents/credentials/validate", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/agent_credential_validation.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Agents().CreateValidate(context.Background(), &workos.AgentsCreateValidateParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestAgents_GetRegistration(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/agents/registrations/test_id", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/agent_registration.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Agents().GetRegistration(context.Background(), "test_id")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "agent_reg_01EHWNCE74X7JSDV0X3SZ3KJNY", result.ID)
	require.Equal(t, "org_01EHQMYV6MBK39QC5PZXHY59C3", result.OrganizationID)
	require.Equal(t, "2026-01-15T12:00:00.000Z", result.CreatedAt)
}

func TestAgents_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.Agents().UpdateAttempts(context.Background(), &workos.AgentsUpdateAttemptsParams{})
	require.IsType(t, &workos.AuthenticationError{}, err)
}

func TestAgents_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.Agents().UpdateAttempts(context.Background(), &workos.AgentsUpdateAttemptsParams{})
	require.IsType(t, &workos.NotFoundError{}, err)
}

func TestAgents_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.Agents().UpdateAttempts(context.Background(), &workos.AgentsUpdateAttemptsParams{})
	require.IsType(t, &workos.UnprocessableEntityError{}, err)
}
