// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// apiKeyService handles ApiKeys operations.
type apiKeyService struct {
	client *Client
}

// APIKeysCreateValidationsParams contains the parameters for CreateValidations.
type APIKeysCreateValidationsParams struct {
	Value string `json:"value"`
}

// CreateValidations validateAPIKey
// Validate an API key value and return the API key object if valid.
func (s *apiKeyService) CreateValidations(ctx context.Context, params *APIKeysCreateValidationsParams, opts ...RequestOption) (*APIKeyValidationResponse, error) {
	var result APIKeyValidationResponse
	_, err := s.client.request(ctx, "POST", "/api_keys/validations", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete deleteAnAPIKey
// Permanently deletes an API key. This action cannot be undone. Once deleted, any requests using this API key will fail authentication.
func (s *apiKeyService) Delete(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/api_keys/%s", id), nil, nil, nil, opts)
	return err
}

// APIKeysListOrganizationAPIKeysParams contains the parameters for ListOrganizationAPIKeys.
type APIKeysListOrganizationAPIKeysParams struct {
	Before *string                    `url:"before,omitempty" json:"-"`
	After  *string                    `url:"after,omitempty" json:"-"`
	Limit  *int                       `url:"limit,omitempty" json:"-"`
	Order  *OrganizationsAPIKeysOrder `url:"order,omitempty" json:"-"`
}

// ListOrganizationAPIKeys listAPIKeysForAnOrganization
// Get a list of all API keys for an organization.
func (s *apiKeyService) ListOrganizationAPIKeys(ctx context.Context, organizationID string, params *APIKeysListOrganizationAPIKeysParams, opts ...RequestOption) *Iterator[APIKey] {
	return newIterator[APIKey](ctx, s.client, "GET", fmt.Sprintf("/organizations/%s/api_keys", organizationID), params, "after", "data", opts)
}

// APIKeysCreateOrganizationAPIKeysParams contains the parameters for CreateOrganizationAPIKeys.
type APIKeysCreateOrganizationAPIKeysParams struct {
	Name        string   `json:"name"`
	Permissions []string `json:"permissions,omitempty"`
}

// CreateOrganizationAPIKeys createAnAPIKeyForAnOrganization
// Create a new API key for an organization.
func (s *apiKeyService) CreateOrganizationAPIKeys(ctx context.Context, organizationID string, params *APIKeysCreateOrganizationAPIKeysParams, opts ...RequestOption) (*APIKeyWithValue, error) {
	var result APIKeyWithValue
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/organizations/%s/api_keys", organizationID), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
