// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
	"net/url"
)

// APIKeyService handles ApiKeys operations.
type APIKeyService struct {
	client *Client
}

// APIKeysListOrganizationAPIKeysParams contains the parameters for ListOrganizationAPIKeys.
type APIKeysListOrganizationAPIKeysParams struct {
	PaginationParams
}

// ListOrganizationAPIKeys list API keys for an organization
// Get a list of all API keys for an organization.
func (s *APIKeyService) ListOrganizationAPIKeys(ctx context.Context, organizationID string, params *APIKeysListOrganizationAPIKeysParams, opts ...RequestOption) *Iterator[OrganizationAPIKey] {
	return newIterator[OrganizationAPIKey](ctx, s.client, "GET", fmt.Sprintf("/organizations/%s/api_keys", url.PathEscape(organizationID)), params, "after", "data", opts, map[string]string{"limit": "10", "order": "desc"})
}

// APIKeysCreateOrganizationAPIKeyParams contains the parameters for CreateOrganizationAPIKey.
type APIKeysCreateOrganizationAPIKeyParams struct {
	// Name is the name for the API key.
	Name string `json:"name" url:"-"`
	// Permissions is the permission slugs to assign to the API key.
	Permissions []string `json:"permissions,omitempty" url:"-"`
	// ExpiresAt is the timestamp when the API key should expire. Must be a future timestamp. If omitted, the key does not expire.
	ExpiresAt *string `json:"expires_at,omitempty" url:"-"`
}

// CreateOrganizationAPIKey create an API key for an organization
// Create a new API key for an organization.
func (s *APIKeyService) CreateOrganizationAPIKey(ctx context.Context, organizationID string, params *APIKeysCreateOrganizationAPIKeyParams, opts ...RequestOption) (*OrganizationAPIKeyWithValue, error) {
	var result OrganizationAPIKeyWithValue
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/organizations/%s/api_keys", url.PathEscape(organizationID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// APIKeysCreateValidationParams contains the parameters for CreateValidation.
type APIKeysCreateValidationParams struct {
	// Value is the value for an API key.
	Value string `json:"value" url:"-"`
}

// CreateValidation validate API key
// Validate an API key value and return the API key object if valid.
func (s *APIKeyService) CreateValidation(ctx context.Context, params *APIKeysCreateValidationParams, opts ...RequestOption) (*APIKeyValidationResponse, error) {
	var result APIKeyValidationResponse
	_, err := s.client.request(ctx, "POST", "/api_keys/validations", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete an API key
// Permanently deletes an API key. This action cannot be undone. Once deleted, any requests using this API key will fail authentication.
func (s *APIKeyService) Delete(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/api_keys/%s", url.PathEscape(id)), nil, nil, nil, opts)
	return err
}

// APIKeysCreateExpireParams contains the parameters for CreateExpire.
type APIKeysCreateExpireParams struct {
	// ExpiresAt is when the API key should expire. If omitted or in the past, the key expires immediately. Use null to clear a scheduled future expiration.
	ExpiresAt *string `json:"expires_at,omitempty" url:"-"`
}

// CreateExpire expire an API key
// Expire an API key immediately, schedule a future expiration, or clear a scheduled future expiration.
func (s *APIKeyService) CreateExpire(ctx context.Context, id string, params *APIKeysCreateExpireParams, opts ...RequestOption) (*APIKey, error) {
	var result APIKey
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/api_keys/%s/expire", url.PathEscape(id)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
