// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// apiKeyService handles ApiKeys operations.
type apiKeyService struct {
	client *Client
}

// APIKeysCreateValidationParams contains the parameters for CreateValidation.
type APIKeysCreateValidationParams struct {
	// Value is the value for an API key.
	Value string `json:"value"`
}

// CreateValidation validate API key
// Validate an API key value and return the API key object if valid.
func (s *apiKeyService) CreateValidation(ctx context.Context, params *APIKeysCreateValidationParams, opts ...RequestOption) (*APIKeyValidationResponse, error) {
	var result APIKeyValidationResponse
	_, err := s.client.request(ctx, "POST", "/api_keys/validations", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete delete an API key
// Permanently deletes an API key. This action cannot be undone. Once deleted, any requests using this API key will fail authentication.
func (s *apiKeyService) Delete(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/api_keys/%s", id), nil, nil, nil, opts)
	return err
}

// APIKeysListOrganizationAPIKeysParams contains the parameters for ListOrganizationAPIKeys.
type APIKeysListOrganizationAPIKeysParams struct {
	PaginationParams
}

// ListOrganizationAPIKeys list API keys for an organization
// Get a list of all API keys for an organization.
func (s *apiKeyService) ListOrganizationAPIKeys(ctx context.Context, organizationID string, params *APIKeysListOrganizationAPIKeysParams, opts ...RequestOption) *Iterator[APIKey] {
	return newIterator[APIKey](ctx, s.client, "GET", fmt.Sprintf("/organizations/%s/api_keys", organizationID), params, "after", "data", opts)
}

// APIKeysCreateOrganizationAPIKeyParams contains the parameters for CreateOrganizationAPIKey.
type APIKeysCreateOrganizationAPIKeyParams struct {
	// Name is the name for the API key.
	Name string `json:"name"`
	// Permissions is the permission slugs to assign to the API key.
	Permissions []string `json:"permissions,omitempty"`
}

// CreateOrganizationAPIKey create an API key for an organization
// Create a new API key for an organization.
func (s *apiKeyService) CreateOrganizationAPIKey(ctx context.Context, organizationID string, params *APIKeysCreateOrganizationAPIKeyParams, opts ...RequestOption) (*APIKeyWithValue, error) {
	var result APIKeyWithValue
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/organizations/%s/api_keys", organizationID), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
