// Code generated by oagen. DO NOT EDIT.

package workos_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/workos/workos-go/v7"
)

func TestAuditLogs_GetOrganizationAuditLogsRetention(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/organizations/test_id/audit_logs_retention", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/audit_logs_retention_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.AuditLogs().GetOrganizationAuditLogsRetention(context.Background(), "test_id")
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestAuditLogs_UpdateOrganizationAuditLogsRetention(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/organizations/test_id/audit_logs_retention", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/audit_logs_retention_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.AuditLogs().UpdateOrganizationAuditLogsRetention(context.Background(), "test_id", &workos.AuditLogsUpdateOrganizationAuditLogsRetentionParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestAuditLogs_ListActions(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/audit_logs/actions", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_audit_log_action_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.AuditLogs().ListActions(context.Background(), &workos.AuditLogsListActionsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestAuditLogs_ListActions_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.AuditLogs().ListActions(context.Background(), &workos.AuditLogsListActionsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestAuditLogs_ListActionSchemas(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/audit_logs/actions/test_actionName/schemas", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_audit_log_schema_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.AuditLogs().ListActionSchemas(context.Background(), "test_actionName", &workos.AuditLogsListActionSchemasParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestAuditLogs_ListActionSchemas_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.AuditLogs().ListActionSchemas(context.Background(), "test_actionName", &workos.AuditLogsListActionSchemasParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestAuditLogs_CreateSchema(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/audit_logs/actions/test_actionName/schemas", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/audit_log_schema_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.AuditLogs().CreateSchema(context.Background(), "test_actionName", &workos.AuditLogsCreateSchemaParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "2026-01-15T12:00:00.000Z", result.CreatedAt)
}

func TestAuditLogs_CreateEvent(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/audit_logs/events", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/audit_log_event_create_response.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.AuditLogs().CreateEvent(context.Background(), &workos.AuditLogsCreateEventParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestAuditLogs_CreateExport(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/audit_logs/exports", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/audit_log_export_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.AuditLogs().CreateExport(context.Background(), &workos.AuditLogsCreateExportParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "audit_log_export_01GBZK5MP7TD1YCFQHFR22180V", result.ID)
	require.Equal(t, "2026-01-15T12:00:00.000Z", result.CreatedAt)
	require.Equal(t, "2026-01-15T12:00:00.000Z", result.UpdatedAt)
}

func TestAuditLogs_GetExport(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/audit_logs/exports/test_auditLogExportId", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/audit_log_export_json.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.AuditLogs().GetExport(context.Background(), "test_auditLogExportId")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "audit_log_export_01GBZK5MP7TD1YCFQHFR22180V", result.ID)
	require.Equal(t, "2026-01-15T12:00:00.000Z", result.CreatedAt)
	require.Equal(t, "2026-01-15T12:00:00.000Z", result.UpdatedAt)
}

func TestAuditLogs_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.AuditLogs().GetOrganizationAuditLogsRetention(context.Background(), "test_id")
	require.IsType(t, &workos.AuthenticationError{}, err)
}

func TestAuditLogs_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.AuditLogs().GetOrganizationAuditLogsRetention(context.Background(), "test_id")
	require.IsType(t, &workos.NotFoundError{}, err)
}

func TestAuditLogs_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.AuditLogs().GetOrganizationAuditLogsRetention(context.Background(), "test_id")
	require.IsType(t, &workos.UnprocessableEntityError{}, err)
}
