// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// auditLogService handles AuditLogs operations.
type auditLogService struct {
	client *Client
}

// ListOrganizationAuditLogsRetention get Retention
// Get the configured event retention period for the given Organization.
func (s *auditLogService) ListOrganizationAuditLogsRetention(ctx context.Context, id string, opts ...RequestOption) (*AuditLogsRetentionJSON, error) {
	var result AuditLogsRetentionJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/organizations/%s/audit_logs_retention", id), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuditLogsUpdateOrganizationAuditLogsRetentionParams contains the parameters for UpdateOrganizationAuditLogsRetention.
type AuditLogsUpdateOrganizationAuditLogsRetentionParams struct {
	// RetentionPeriodInDays is the number of days Audit Log events will be retained. Valid values are `30` and `365`.
	RetentionPeriodInDays int `json:"retention_period_in_days"`
}

// UpdateOrganizationAuditLogsRetention set Retention
// Set the event retention period for the given Organization.
func (s *auditLogService) UpdateOrganizationAuditLogsRetention(ctx context.Context, id string, params *AuditLogsUpdateOrganizationAuditLogsRetentionParams, opts ...RequestOption) (*AuditLogsRetentionJSON, error) {
	var result AuditLogsRetentionJSON
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/organizations/%s/audit_logs_retention", id), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuditLogsListActionsParams contains the parameters for ListActions.
type AuditLogsListActionsParams struct {
	PaginationParams
}

// ListActions list Actions
// Get a list of all Audit Log actions in the current environment.
func (s *auditLogService) ListActions(ctx context.Context, params *AuditLogsListActionsParams, opts ...RequestOption) *Iterator[AuditLogActionJSON] {
	return newIterator[AuditLogActionJSON](ctx, s.client, "GET", "/audit_logs/actions", params, "after", "data", opts)
}

// AuditLogsListActionSchemasParams contains the parameters for ListActionSchemas.
type AuditLogsListActionSchemasParams struct {
	PaginationParams
}

// ListActionSchemas list Schemas
// Get a list of all schemas for the Audit Logs action identified by `:name`.
func (s *auditLogService) ListActionSchemas(ctx context.Context, actionName string, params *AuditLogsListActionSchemasParams, opts ...RequestOption) *Iterator[AuditLogSchemaJSON] {
	return newIterator[AuditLogSchemaJSON](ctx, s.client, "GET", fmt.Sprintf("/audit_logs/actions/%s/schemas", actionName), params, "after", "data", opts)
}

// AuditLogsCreateSchemaParams contains the parameters for CreateSchema.
type AuditLogsCreateSchemaParams struct {
	// Actor is the metadata schema for the actor.
	Actor *AuditLogSchemaActor `json:"actor,omitempty"`
	// Targets is the list of targets for the schema.
	Targets []*AuditLogSchemaTarget `json:"targets"`
	// Metadata is optional JSON schema for event metadata.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// CreateSchema create Schema
// Creates a new Audit Log schema used to validate the payload of incoming Audit Log Events. If the `action` does not exist, it will also be created.
func (s *auditLogService) CreateSchema(ctx context.Context, actionName string, params *AuditLogsCreateSchemaParams, opts ...RequestOption) (*AuditLogSchemaJSON, error) {
	var result AuditLogSchemaJSON
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/audit_logs/actions/%s/schemas", actionName), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuditLogsCreateEventParams contains the parameters for CreateEvent.
type AuditLogsCreateEventParams struct {
	// OrganizationID is the unique ID of the Organization.
	OrganizationID string `json:"organization_id"`
	// Event is the audit log event to create.
	Event *AuditLogEvent `json:"event"`
}

// CreateEvent create Event
// Create an Audit Log Event.
// This API supports idempotency which guarantees that performing the same operation multiple times will have the same result as if the operation were performed only once. This is handy in situations where you may need to retry a request due to a failure or prevent accidental duplicate requests from creating more than one resource.
// To achieve idempotency, you can add `Idempotency-Key` request header to a Create Event request with a unique string as the value. Each subsequent request matching this unique string will return the same response. We suggest using [v4 UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier) for idempotency keys to avoid collisions.
// Idempotency keys expire after 24 hours. The API will generate a new response if you submit a request with an expired key.
func (s *auditLogService) CreateEvent(ctx context.Context, params *AuditLogsCreateEventParams, opts ...RequestOption) (*AuditLogEventCreateResponse, error) {
	var result AuditLogEventCreateResponse
	_, err := s.client.request(ctx, "POST", "/audit_logs/events", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuditLogsCreateExportParams contains the parameters for CreateExport.
type AuditLogsCreateExportParams struct {
	// OrganizationID is the unique ID of the Organization.
	OrganizationID string `json:"organization_id"`
	// RangeStart is iso-8601 value for start of the export range.
	RangeStart string `json:"range_start"`
	// RangeEnd is iso-8601 value for end of the export range.
	RangeEnd string `json:"range_end"`
	// Actions is list of actions to filter against.
	Actions []string `json:"actions,omitempty"`
	// Actors is deprecated. Use `actor_names` instead.
	//
	// Deprecated: this field is deprecated.
	Actors []string `json:"actors,omitempty"`
	// ActorNames is list of actor names to filter against.
	ActorNames []string `json:"actor_names,omitempty"`
	// ActorIDs is list of actor IDs to filter against.
	ActorIDs []string `json:"actor_ids,omitempty"`
	// Targets is list of target types to filter against.
	Targets []string `json:"targets,omitempty"`
}

// CreateExport create Export
// Create an Audit Log Export. Exports are scoped to a single organization within a specified date range.
func (s *auditLogService) CreateExport(ctx context.Context, params *AuditLogsCreateExportParams, opts ...RequestOption) (*AuditLogExportJSON, error) {
	var result AuditLogExportJSON
	_, err := s.client.request(ctx, "POST", "/audit_logs/exports", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetExport get Export
// Get an Audit Log Export. The URL will expire after 10 minutes. If the export is needed again at a later time, refetching the export will regenerate the URL.
func (s *auditLogService) GetExport(ctx context.Context, auditLogExportID string, opts ...RequestOption) (*AuditLogExportJSON, error) {
	var result AuditLogExportJSON
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/audit_logs/exports/%s", auditLogExportID), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
