// Code generated by oagen. DO NOT EDIT.

package workos_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/workos/workos-go/v7"
)

func TestAuthorization_Check(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/authorization/organization_memberships/test_organization_membership_id/check", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/authorization_check.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().Check(context.Background(), "test_organization_membership_id", &workos.AuthorizationCheckParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestAuthorization_ListOrganizationMembershipResources(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/organization_memberships/test_organization_membership_id/resources", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_authorization_resource.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListOrganizationMembershipResources(context.Background(), "test_organization_membership_id", &workos.AuthorizationListOrganizationMembershipResourcesParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestAuthorization_ListOrganizationMembershipResources_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListOrganizationMembershipResources(context.Background(), "test_organization_membership_id", &workos.AuthorizationListOrganizationMembershipResourcesParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestAuthorization_ListResourcePermissions(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_id/permissions", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_authorization_permission.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListResourcePermissions(context.Background(), "test_organization_membership_id", "test_resource_id", &workos.AuthorizationListResourcePermissionsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestAuthorization_ListResourcePermissions_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListResourcePermissions(context.Background(), "test_organization_membership_id", "test_resource_id", &workos.AuthorizationListResourcePermissionsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestAuthorization_ListEffectivePermissionsByExternalID(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_type_slug/test_external_id/permissions", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_authorization_permission.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListEffectivePermissionsByExternalID(context.Background(), "test_organization_membership_id", "test_resource_type_slug", "test_external_id", &workos.AuthorizationListEffectivePermissionsByExternalIDParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestAuthorization_ListEffectivePermissionsByExternalID_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListEffectivePermissionsByExternalID(context.Background(), "test_organization_membership_id", "test_resource_type_slug", "test_external_id", &workos.AuthorizationListEffectivePermissionsByExternalIDParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestAuthorization_ListOrganizationMembershipRoleAssignments(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/organization_memberships/test_organization_membership_id/role_assignments", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_role_assignment.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListOrganizationMembershipRoleAssignments(context.Background(), "test_organization_membership_id", &workos.AuthorizationListOrganizationMembershipRoleAssignmentsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestAuthorization_ListOrganizationMembershipRoleAssignments_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListOrganizationMembershipRoleAssignments(context.Background(), "test_organization_membership_id", &workos.AuthorizationListOrganizationMembershipRoleAssignmentsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestAuthorization_AssignRole(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/authorization/organization_memberships/test_organization_membership_id/role_assignments", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role_assignment.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().AssignRole(context.Background(), "test_organization_membership_id", &workos.AuthorizationAssignRoleParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_assignment_01HXYZ123456789ABCDEFGH", result.ID)
	require.Equal(t, "2026-01-15T12:00:00.000Z", result.CreatedAt)
	require.Equal(t, "2026-01-15T12:00:00.000Z", result.UpdatedAt)
}

func TestAuthorization_RemoveRole(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/authorization/organization_memberships/test_organization_membership_id/role_assignments", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Authorization().RemoveRole(context.Background(), "test_organization_membership_id", &workos.AuthorizationRemoveRoleParams{})
	require.NoError(t, err)
}

func TestAuthorization_DeleteOrganizationMembershipRoleAssignment(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/authorization/organization_memberships/test_organization_membership_id/role_assignments/test_role_assignment_id", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Authorization().DeleteOrganizationMembershipRoleAssignment(context.Background(), "test_organization_membership_id", "test_role_assignment_id")
	require.NoError(t, err)
}

func TestAuthorization_ListOrganizationRoles(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/organizations/test_organizationId/roles", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role_list.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().ListOrganizationRoles(context.Background(), "test_organizationId")
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestAuthorization_CreateOrganizationRole(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/authorization/organizations/test_organizationId/roles", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().CreateOrganizationRole(context.Background(), "test_organizationId", &workos.AuthorizationCreateOrganizationRoleParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_01EHQMYV6MBK39QC5PZXHY59C3", result.ID)
	require.Equal(t, "admin", result.Slug)
	require.Equal(t, "Admin", result.Name)
}

func TestAuthorization_GetOrganizationRole(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/organizations/test_organizationId/roles/test_slug", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().GetOrganizationRole(context.Background(), "test_organizationId", "test_slug")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_01EHQMYV6MBK39QC5PZXHY59C3", result.ID)
	require.Equal(t, "admin", result.Slug)
	require.Equal(t, "Admin", result.Name)
}

func TestAuthorization_UpdateOrganizationRole(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/authorization/organizations/test_organizationId/roles/test_slug", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().UpdateOrganizationRole(context.Background(), "test_organizationId", "test_slug", &workos.AuthorizationUpdateOrganizationRoleParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_01EHQMYV6MBK39QC5PZXHY59C3", result.ID)
	require.Equal(t, "admin", result.Slug)
	require.Equal(t, "Admin", result.Name)
}

func TestAuthorization_DeleteOrganizationRole(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/authorization/organizations/test_organizationId/roles/test_slug", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Authorization().DeleteOrganizationRole(context.Background(), "test_organizationId", "test_slug")
	require.NoError(t, err)
}

func TestAuthorization_CreateRolePermission(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/authorization/organizations/test_organizationId/roles/test_slug/permissions", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().CreateRolePermission(context.Background(), "test_organizationId", "test_slug", &workos.AuthorizationCreateRolePermissionParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_01EHQMYV6MBK39QC5PZXHY59C3", result.ID)
	require.Equal(t, "admin", result.Slug)
	require.Equal(t, "Admin", result.Name)
}

func TestAuthorization_UpdateRolePermissions(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/authorization/organizations/test_organizationId/roles/test_slug/permissions", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().UpdateRolePermissions(context.Background(), "test_organizationId", "test_slug", &workos.AuthorizationUpdateRolePermissionsParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_01EHQMYV6MBK39QC5PZXHY59C3", result.ID)
	require.Equal(t, "admin", result.Slug)
	require.Equal(t, "Admin", result.Name)
}

func TestAuthorization_DeleteRolePermission(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/authorization/organizations/test_organizationId/roles/test_slug/permissions/test_permissionSlug", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Authorization().DeleteRolePermission(context.Background(), "test_organizationId", "test_slug", "test_permissionSlug")
	require.NoError(t, err)
}

func TestAuthorization_GetOrganizationResource(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/authorization_resource.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().GetOrganizationResource(context.Background(), "test_organization_id", "test_resource_type_slug", "test_external_id")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "authz_resource_01HXYZ123456789ABCDEFGH", result.ID)
	require.Equal(t, "Website Redesign", result.Name)
	require.Equal(t, "org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationID)
}

func TestAuthorization_UpdateOrganizationResource(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/authorization_resource.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().UpdateOrganizationResource(context.Background(), "test_organization_id", "test_resource_type_slug", "test_external_id", &workos.AuthorizationUpdateOrganizationResourceParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "authz_resource_01HXYZ123456789ABCDEFGH", result.ID)
	require.Equal(t, "Website Redesign", result.Name)
	require.Equal(t, "org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationID)
}

func TestAuthorization_DeleteOrganizationResource(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Authorization().DeleteOrganizationResource(context.Background(), "test_organization_id", "test_resource_type_slug", "test_external_id", &workos.AuthorizationDeleteOrganizationResourceParams{})
	require.NoError(t, err)
}

func TestAuthorization_ListResourceOrganizationMemberships(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id/organization_memberships", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_user_organization_membership_base_list_data.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListResourceOrganizationMemberships(context.Background(), "test_organization_id", "test_resource_type_slug", "test_external_id", &workos.AuthorizationListResourceOrganizationMembershipsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestAuthorization_ListResourceOrganizationMemberships_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListResourceOrganizationMemberships(context.Background(), "test_organization_id", "test_resource_type_slug", "test_external_id", &workos.AuthorizationListResourceOrganizationMembershipsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestAuthorization_ListResources(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/resources", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_authorization_resource.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListResources(context.Background(), &workos.AuthorizationListResourcesParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestAuthorization_ListResources_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListResources(context.Background(), &workos.AuthorizationListResourcesParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestAuthorization_CreateResource(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/authorization/resources", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/authorization_resource.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().CreateResource(context.Background(), &workos.AuthorizationCreateResourceParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "authz_resource_01HXYZ123456789ABCDEFGH", result.ID)
	require.Equal(t, "Website Redesign", result.Name)
	require.Equal(t, "org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationID)
}

func TestAuthorization_GetResource(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/resources/test_resource_id", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/authorization_resource.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().GetResource(context.Background(), "test_resource_id")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "authz_resource_01HXYZ123456789ABCDEFGH", result.ID)
	require.Equal(t, "Website Redesign", result.Name)
	require.Equal(t, "org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationID)
}

func TestAuthorization_UpdateResource(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/authorization/resources/test_resource_id", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/authorization_resource.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().UpdateResource(context.Background(), "test_resource_id", &workos.AuthorizationUpdateResourceParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "authz_resource_01HXYZ123456789ABCDEFGH", result.ID)
	require.Equal(t, "Website Redesign", result.Name)
	require.Equal(t, "org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationID)
}

func TestAuthorization_DeleteResource(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/authorization/resources/test_resource_id", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Authorization().DeleteResource(context.Background(), "test_resource_id", &workos.AuthorizationDeleteResourceParams{})
	require.NoError(t, err)
}

func TestAuthorization_ListMembershipsForResource(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/resources/test_resource_id/organization_memberships", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_user_organization_membership_base_list_data.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListMembershipsForResource(context.Background(), "test_resource_id", &workos.AuthorizationListMembershipsForResourceParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestAuthorization_ListMembershipsForResource_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListMembershipsForResource(context.Background(), "test_resource_id", &workos.AuthorizationListMembershipsForResourceParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestAuthorization_ListEnvironmentRoles(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/roles", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role_list.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().ListEnvironmentRoles(context.Background())
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestAuthorization_CreateEnvironmentRole(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/authorization/roles", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().CreateEnvironmentRole(context.Background(), &workos.AuthorizationCreateEnvironmentRoleParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_01EHQMYV6MBK39QC5PZXHY59C3", result.ID)
	require.Equal(t, "admin", result.Slug)
	require.Equal(t, "Admin", result.Name)
}

func TestAuthorization_GetEnvironmentRole(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/roles/test_slug", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().GetEnvironmentRole(context.Background(), "test_slug")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_01EHQMYV6MBK39QC5PZXHY59C3", result.ID)
	require.Equal(t, "admin", result.Slug)
	require.Equal(t, "Admin", result.Name)
}

func TestAuthorization_UpdateEnvironmentRole(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/authorization/roles/test_slug", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().UpdateEnvironmentRole(context.Background(), "test_slug", &workos.AuthorizationUpdateEnvironmentRoleParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_01EHQMYV6MBK39QC5PZXHY59C3", result.ID)
	require.Equal(t, "admin", result.Slug)
	require.Equal(t, "Admin", result.Name)
}

func TestAuthorization_AddEnvironmentRolePermission(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/authorization/roles/test_slug/permissions", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().AddEnvironmentRolePermission(context.Background(), "test_slug", &workos.AuthorizationAddEnvironmentRolePermissionParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_01EHQMYV6MBK39QC5PZXHY59C3", result.ID)
	require.Equal(t, "admin", result.Slug)
	require.Equal(t, "Admin", result.Name)
}

func TestAuthorization_SetEnvironmentRolePermissions(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/authorization/roles/test_slug/permissions", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/role.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().SetEnvironmentRolePermissions(context.Background(), "test_slug", &workos.AuthorizationSetEnvironmentRolePermissionsParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "role_01EHQMYV6MBK39QC5PZXHY59C3", result.ID)
	require.Equal(t, "admin", result.Slug)
	require.Equal(t, "Admin", result.Name)
}

func TestAuthorization_ListPermissions(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/permissions", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_authorization_permission.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListPermissions(context.Background(), &workos.AuthorizationListPermissionsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestAuthorization_ListPermissions_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Authorization().ListPermissions(context.Background(), &workos.AuthorizationListPermissionsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestAuthorization_CreatePermission(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/authorization/permissions", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/permission.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().CreatePermission(context.Background(), &workos.AuthorizationCreatePermissionParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "perm_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "documents:read", result.Slug)
	require.Equal(t, "View Documents", result.Name)
}

func TestAuthorization_GetPermission(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/authorization/permissions/test_slug", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/authorization_permission.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().GetPermission(context.Background(), "test_slug")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "perm_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "documents:read", result.Slug)
	require.Equal(t, "View Documents", result.Name)
}

func TestAuthorization_UpdatePermission(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/authorization/permissions/test_slug", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/authorization_permission.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Authorization().UpdatePermission(context.Background(), "test_slug", &workos.AuthorizationUpdatePermissionParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "perm_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "documents:read", result.Slug)
	require.Equal(t, "View Documents", result.Name)
}

func TestAuthorization_DeletePermission(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/authorization/permissions/test_slug", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Authorization().DeletePermission(context.Background(), "test_slug")
	require.NoError(t, err)
}

func TestAuthorization_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.Authorization().Check(context.Background(), "test_organization_membership_id", &workos.AuthorizationCheckParams{})
	require.IsType(t, &workos.AuthenticationError{}, err)
}

func TestAuthorization_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.Authorization().Check(context.Background(), "test_organization_membership_id", &workos.AuthorizationCheckParams{})
	require.IsType(t, &workos.NotFoundError{}, err)
}

func TestAuthorization_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.Authorization().Check(context.Background(), "test_organization_membership_id", &workos.AuthorizationCheckParams{})
	require.IsType(t, &workos.UnprocessableEntityError{}, err)
}
