// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// authorizationService handles Authorization operations.
type authorizationService struct {
	client *Client
}

// AuthorizationCheckOrganizationMembershipParams contains the parameters for CheckOrganizationMembership.
type AuthorizationCheckOrganizationMembershipParams struct {
	// PermissionSlug is the slug of the permission to check.
	PermissionSlug string `json:"permission_slug"`
	// ResourceID is the ID of the resource.
	ResourceID *string `json:"resource_id,omitempty"`
	// ResourceExternalID is the external ID of the resource.
	ResourceExternalID *string `json:"resource_external_id,omitempty"`
	// ResourceTypeSlug is the slug of the resource type.
	ResourceTypeSlug *string `json:"resource_type_slug,omitempty"`
}

// CheckOrganizationMembership check authorization
// Check if an organization membership has a specific permission on a resource. Supports identification by resource_id OR by resource_external_id + resource_type_slug.
func (s *authorizationService) CheckOrganizationMembership(ctx context.Context, organizationMembershipID string, params *AuthorizationCheckOrganizationMembershipParams, opts ...RequestOption) (*AuthorizationCheck, error) {
	var result AuthorizationCheck
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/authorization/organization_memberships/%s/check", organizationMembershipID), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationListOrganizationMembershipResourcesParams contains the parameters for ListOrganizationMembershipResources.
type AuthorizationListOrganizationMembershipResourcesParams struct {
	PaginationParams
	// PermissionSlug is the permission slug to filter by. Only child resources where the organization membership has this permission are returned.
	PermissionSlug string `url:"permission_slug" json:"-"`
	// ParentResourceID is the WorkOS ID of the parent resource. Provide this or both `parent_resource_external_id` and `parent_resource_type_slug`, but not both.
	ParentResourceID *string `url:"parent_resource_id,omitempty" json:"-"`
	// ParentResourceTypeSlug is the slug of the parent resource type. Must be provided together with `parent_resource_external_id`.
	ParentResourceTypeSlug *string `url:"parent_resource_type_slug,omitempty" json:"-"`
	// ParentResourceExternalID is the application-specific external identifier of the parent resource. Must be provided together with `parent_resource_type_slug`.
	ParentResourceExternalID *string `url:"parent_resource_external_id,omitempty" json:"-"`
}

// ListOrganizationMembershipResources list resources for organization membership
// Returns all child resources of a parent resource where the organization membership has a specific permission. This is useful for resource discovery—answering "What projects can this user access in this workspace?"
// You must provide either `parent_resource_id` or both `parent_resource_external_id` and `parent_resource_type_slug` to identify the parent resource.
func (s *authorizationService) ListOrganizationMembershipResources(ctx context.Context, organizationMembershipID string, params *AuthorizationListOrganizationMembershipResourcesParams, opts ...RequestOption) *Iterator[AuthorizationResource] {
	return newIterator[AuthorizationResource](ctx, s.client, "GET", fmt.Sprintf("/authorization/organization_memberships/%s/resources", organizationMembershipID), params, "after", "data", opts)
}

// AuthorizationListOrganizationMembershipRoleAssignmentsParams contains the parameters for ListOrganizationMembershipRoleAssignments.
type AuthorizationListOrganizationMembershipRoleAssignmentsParams struct {
	PaginationParams
}

// ListOrganizationMembershipRoleAssignments list role assignments
// List all role assignments for an organization membership. This returns all roles that have been assigned to the user on resources, including organization-level and sub-resource roles.
func (s *authorizationService) ListOrganizationMembershipRoleAssignments(ctx context.Context, organizationMembershipID string, params *AuthorizationListOrganizationMembershipRoleAssignmentsParams, opts ...RequestOption) *Iterator[RoleAssignment] {
	return newIterator[RoleAssignment](ctx, s.client, "GET", fmt.Sprintf("/authorization/organization_memberships/%s/role_assignments", organizationMembershipID), params, "after", "data", opts)
}

// AuthorizationCreateOrganizationMembershipRoleAssignmentsParams contains the parameters for CreateOrganizationMembershipRoleAssignments.
type AuthorizationCreateOrganizationMembershipRoleAssignmentsParams struct {
	// RoleSlug is the slug of the role to assign.
	RoleSlug string `json:"role_slug"`
	// ResourceID is the ID of the resource. Use either this or `resource_external_id` and `resource_type_slug`.
	ResourceID *string `json:"resource_id,omitempty"`
	// ResourceExternalID is the external ID of the resource. Requires `resource_type_slug`.
	ResourceExternalID *string `json:"resource_external_id,omitempty"`
	// ResourceTypeSlug is the resource type slug. Required with `resource_external_id`.
	ResourceTypeSlug *string `json:"resource_type_slug,omitempty"`
}

// CreateOrganizationMembershipRoleAssignments assign a role
// Assign a role to an organization membership on a specific resource.
func (s *authorizationService) CreateOrganizationMembershipRoleAssignments(ctx context.Context, organizationMembershipID string, params *AuthorizationCreateOrganizationMembershipRoleAssignmentsParams, opts ...RequestOption) (*RoleAssignment, error) {
	var result RoleAssignment
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/authorization/organization_memberships/%s/role_assignments", organizationMembershipID), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationDeleteOrganizationMembershipRoleAssignmentsParams contains the parameters for DeleteOrganizationMembershipRoleAssignments.
type AuthorizationDeleteOrganizationMembershipRoleAssignmentsParams struct {
	// RoleSlug is the slug of the role to remove.
	RoleSlug string `json:"role_slug"`
	// ResourceID is the ID of the resource. Use either this or `resource_external_id` and `resource_type_slug`.
	ResourceID *string `json:"resource_id,omitempty"`
	// ResourceExternalID is the external ID of the resource. Requires `resource_type_slug`.
	ResourceExternalID *string `json:"resource_external_id,omitempty"`
	// ResourceTypeSlug is the resource type slug. Required with `resource_external_id`.
	ResourceTypeSlug *string `json:"resource_type_slug,omitempty"`
}

// DeleteOrganizationMembershipRoleAssignments remove a role assignment
// Remove a role assignment by role slug and resource.
func (s *authorizationService) DeleteOrganizationMembershipRoleAssignments(ctx context.Context, organizationMembershipID string, params *AuthorizationDeleteOrganizationMembershipRoleAssignmentsParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/authorization/organization_memberships/%s/role_assignments", organizationMembershipID), nil, params, nil, opts)
	return err
}

// DeleteOrganizationMembershipRoleAssignment remove a role assignment by ID
// Remove a role assignment using its ID.
func (s *authorizationService) DeleteOrganizationMembershipRoleAssignment(ctx context.Context, organizationMembershipID string, roleAssignmentID string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/authorization/organization_memberships/%s/role_assignments/%s", organizationMembershipID, roleAssignmentID), nil, nil, nil, opts)
	return err
}

// ListOrganizationRoles list organization roles
// Get a list of all roles that apply to an organization. This includes both environment roles and organization-specific roles, returned in priority order.
func (s *authorizationService) ListOrganizationRoles(ctx context.Context, organizationID string, opts ...RequestOption) (*RoleList, error) {
	var result RoleList
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/authorization/organizations/%s/roles", organizationID), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationCreateOrganizationRolesParams contains the parameters for CreateOrganizationRoles.
type AuthorizationCreateOrganizationRolesParams struct {
	// Slug is a unique identifier for the role within the organization. When provided, must begin with 'org-' and contain only lowercase letters, numbers, hyphens, and underscores. When omitted, a slug is auto-generated from the role name and a random suffix.
	Slug *string `json:"slug,omitempty"`
	// Name is a descriptive name for the role.
	Name string `json:"name"`
	// Description is an optional description of the role's purpose.
	Description *string `json:"description,omitempty"`
	// ResourceTypeSlug is the slug of the resource type the role is scoped to.
	ResourceTypeSlug *string `json:"resource_type_slug,omitempty"`
}

// CreateOrganizationRoles create a custom organization role
// Create a new custom organization role. When slug is omitted, it is auto-generated from the role name.
func (s *authorizationService) CreateOrganizationRoles(ctx context.Context, organizationID string, params *AuthorizationCreateOrganizationRolesParams, opts ...RequestOption) (*Role, error) {
	var result Role
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/authorization/organizations/%s/roles", organizationID), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOrganizationRole get an organization role
// Retrieve a role that applies to an organization by its slug. This can return either an environment role or an organization-specific role.
func (s *authorizationService) GetOrganizationRole(ctx context.Context, organizationID string, slug string, opts ...RequestOption) (*Role, error) {
	var result Role
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/authorization/organizations/%s/roles/%s", organizationID, slug), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationUpdateOrganizationRoleParams contains the parameters for UpdateOrganizationRole.
type AuthorizationUpdateOrganizationRoleParams struct {
	// Name is a descriptive name for the role.
	Name *string `json:"name,omitempty"`
	// Description is an optional description of the role's purpose.
	Description *string `json:"description,omitempty"`
}

// UpdateOrganizationRole update an organization role
// Update an existing custom organization role. Only the fields provided in the request body will be updated.
func (s *authorizationService) UpdateOrganizationRole(ctx context.Context, organizationID string, slug string, params *AuthorizationUpdateOrganizationRoleParams, opts ...RequestOption) (*Role, error) {
	var result Role
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/authorization/organizations/%s/roles/%s", organizationID, slug), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteOrganizationRole delete a custom organization role
// Delete an existing custom organization role.
func (s *authorizationService) DeleteOrganizationRole(ctx context.Context, organizationID string, slug string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/authorization/organizations/%s/roles/%s", organizationID, slug), nil, nil, nil, opts)
	return err
}

// AuthorizationCreateRolePermissionsParams contains the parameters for CreateRolePermissions.
type AuthorizationCreateRolePermissionsParams struct {
	// Slug is the slug of the permission to add to the role.
	Slug string `json:"slug"`
}

// CreateRolePermissions add a permission to an organization role
// Add a single permission to an organization role. If the permission is already assigned to the role, this operation has no effect.
func (s *authorizationService) CreateRolePermissions(ctx context.Context, organizationID string, slug string, params *AuthorizationCreateRolePermissionsParams, opts ...RequestOption) (*Role, error) {
	var result Role
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/authorization/organizations/%s/roles/%s/permissions", organizationID, slug), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationUpdateRolePermissionsParams contains the parameters for UpdateRolePermissions.
type AuthorizationUpdateRolePermissionsParams struct {
	// Permissions is the permission slugs to assign to the role.
	Permissions []string `json:"permissions"`
}

// UpdateRolePermissions set permissions for a role
// Replace all permissions on a role with the provided list.
func (s *authorizationService) UpdateRolePermissions(ctx context.Context, organizationID string, slug string, params *AuthorizationUpdateRolePermissionsParams, opts ...RequestOption) (*Role, error) {
	var result Role
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/authorization/organizations/%s/roles/%s/permissions", organizationID, slug), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteRolePermission remove a permission from an organization role
// Remove a single permission from an organization role by its slug.
func (s *authorizationService) DeleteRolePermission(ctx context.Context, organizationID string, slug string, permissionSlug string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/authorization/organizations/%s/roles/%s/permissions/%s", organizationID, slug, permissionSlug), nil, nil, nil, opts)
	return err
}

// GetOrganizationResource get a resource by external ID
// Retrieve the details of an authorization resource by its external ID, organization, and resource type. This is useful when you only have the external ID from your system and need to fetch the full resource details.
func (s *authorizationService) GetOrganizationResource(ctx context.Context, organizationID string, resourceTypeSlug string, externalID string, opts ...RequestOption) (*AuthorizationResource, error) {
	var result AuthorizationResource
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/authorization/organizations/%s/resources/%s/%s", organizationID, resourceTypeSlug, externalID), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationUpdateOrganizationResourceParams contains the parameters for UpdateOrganizationResource.
type AuthorizationUpdateOrganizationResourceParams struct {
	// Name is a display name for the resource.
	Name *string `json:"name,omitempty"`
	// Description is an optional description of the resource.
	Description *string `json:"description,omitempty"`
	// ParentResourceID is the ID of the parent resource.
	ParentResourceID *string `json:"parent_resource_id,omitempty"`
	// ParentResourceExternalID is the external ID of the parent resource.
	ParentResourceExternalID *string `json:"parent_resource_external_id,omitempty"`
	// ParentResourceTypeSlug is the resource type slug of the parent resource.
	ParentResourceTypeSlug *string `json:"parent_resource_type_slug,omitempty"`
}

// UpdateOrganizationResource update a resource by external ID
// Update an existing authorization resource using its external ID.
func (s *authorizationService) UpdateOrganizationResource(ctx context.Context, organizationID string, resourceTypeSlug string, externalID string, params *AuthorizationUpdateOrganizationResourceParams, opts ...RequestOption) (*AuthorizationResource, error) {
	var result AuthorizationResource
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/authorization/organizations/%s/resources/%s/%s", organizationID, resourceTypeSlug, externalID), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationDeleteOrganizationResourceParams contains the parameters for DeleteOrganizationResource.
type AuthorizationDeleteOrganizationResourceParams struct {
	// CascadeDelete is if true, deletes all descendant resources and role assignments. If not set and the resource has children or assignments, the request will fail.
	// Defaults to false.
	CascadeDelete *bool `url:"cascade_delete,omitempty" json:"-"`
}

// DeleteOrganizationResource delete an authorization resource by external ID
// Delete an authorization resource by organization, resource type, and external ID. This also deletes all descendant resources.
func (s *authorizationService) DeleteOrganizationResource(ctx context.Context, organizationID string, resourceTypeSlug string, externalID string, params *AuthorizationDeleteOrganizationResourceParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/authorization/organizations/%s/resources/%s/%s", organizationID, resourceTypeSlug, externalID), params, nil, nil, opts)
	return err
}

// AuthorizationListResourceOrganizationMembershipsParams contains the parameters for ListResourceOrganizationMemberships.
type AuthorizationListResourceOrganizationMembershipsParams struct {
	PaginationParams
	// PermissionSlug is the permission slug to filter by. Only users with this permission on the resource are returned.
	PermissionSlug string `url:"permission_slug" json:"-"`
	// Assignment is filter by assignment type. Use "direct" for direct assignments only, or "indirect" to include inherited assignments.
	Assignment *AuthorizationAssignment `url:"assignment,omitempty" json:"-"`
}

// ListResourceOrganizationMemberships list memberships for a resource by external ID
// Returns all organization memberships that have a specific permission on a resource, using the resource's external ID. This is useful for answering "Who can access this resource?" when you only have the external ID.
func (s *authorizationService) ListResourceOrganizationMemberships(ctx context.Context, organizationID string, resourceTypeSlug string, externalID string, params *AuthorizationListResourceOrganizationMembershipsParams, opts ...RequestOption) *Iterator[UserOrganizationMembershipBaseListData] {
	return newIterator[UserOrganizationMembershipBaseListData](ctx, s.client, "GET", fmt.Sprintf("/authorization/organizations/%s/resources/%s/%s/organization_memberships", organizationID, resourceTypeSlug, externalID), params, "after", "data", opts)
}

// AuthorizationListResourcesParams contains the parameters for ListResources.
type AuthorizationListResourcesParams struct {
	PaginationParams
	// OrganizationID is filter resources by organization ID.
	OrganizationID *string `url:"organization_id,omitempty" json:"-"`
	// ResourceTypeSlug is filter resources by resource type slug.
	ResourceTypeSlug *string `url:"resource_type_slug,omitempty" json:"-"`
	// ParentResourceID is filter resources by parent resource ID.
	ParentResourceID *string `url:"parent_resource_id,omitempty" json:"-"`
	// ParentResourceTypeSlug is filter resources by parent resource type slug.
	ParentResourceTypeSlug *string `url:"parent_resource_type_slug,omitempty" json:"-"`
	// ParentExternalID is filter resources by parent external ID.
	ParentExternalID *string `url:"parent_external_id,omitempty" json:"-"`
	// Search is search resources by name.
	Search *string `url:"search,omitempty" json:"-"`
}

// ListResources list resources
// Get a paginated list of authorization resources.
func (s *authorizationService) ListResources(ctx context.Context, params *AuthorizationListResourcesParams, opts ...RequestOption) *Iterator[AuthorizationResource] {
	return newIterator[AuthorizationResource](ctx, s.client, "GET", "/authorization/resources", params, "after", "data", opts)
}

// AuthorizationCreateResourcesParams contains the parameters for CreateResources.
type AuthorizationCreateResourcesParams struct {
	// ExternalID is an external identifier for the resource.
	ExternalID string `json:"external_id"`
	// Name is a display name for the resource.
	Name string `json:"name"`
	// Description is an optional description of the resource.
	Description *string `json:"description,omitempty"`
	// ResourceTypeSlug is the slug of the resource type.
	ResourceTypeSlug string `json:"resource_type_slug"`
	// OrganizationID is the ID of the organization this resource belongs to.
	OrganizationID string `json:"organization_id"`
	// ParentResourceID is the ID of the parent resource.
	ParentResourceID *string `json:"parent_resource_id,omitempty"`
	// ParentResourceExternalID is the external ID of the parent resource.
	ParentResourceExternalID *string `json:"parent_resource_external_id,omitempty"`
	// ParentResourceTypeSlug is the resource type slug of the parent resource.
	ParentResourceTypeSlug *string `json:"parent_resource_type_slug,omitempty"`
}

// CreateResources create an authorization resource
// Create a new authorization resource.
func (s *authorizationService) CreateResources(ctx context.Context, params *AuthorizationCreateResourcesParams, opts ...RequestOption) (*AuthorizationResource, error) {
	var result AuthorizationResource
	_, err := s.client.request(ctx, "POST", "/authorization/resources", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetResource get a resource
// Retrieve the details of an authorization resource by its ID.
func (s *authorizationService) GetResource(ctx context.Context, resourceID string, opts ...RequestOption) (*AuthorizationResource, error) {
	var result AuthorizationResource
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/authorization/resources/%s", resourceID), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationUpdateResourceParams contains the parameters for UpdateResource.
type AuthorizationUpdateResourceParams struct {
	// Name is a display name for the resource.
	Name *string `json:"name,omitempty"`
	// Description is an optional description of the resource.
	Description *string `json:"description,omitempty"`
	// ParentResourceID is the ID of the parent resource.
	ParentResourceID *string `json:"parent_resource_id,omitempty"`
	// ParentResourceExternalID is the external ID of the parent resource.
	ParentResourceExternalID *string `json:"parent_resource_external_id,omitempty"`
	// ParentResourceTypeSlug is the resource type slug of the parent resource.
	ParentResourceTypeSlug *string `json:"parent_resource_type_slug,omitempty"`
}

// UpdateResource update a resource
// Update an existing authorization resource.
func (s *authorizationService) UpdateResource(ctx context.Context, resourceID string, params *AuthorizationUpdateResourceParams, opts ...RequestOption) (*AuthorizationResource, error) {
	var result AuthorizationResource
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/authorization/resources/%s", resourceID), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationDeleteResourceParams contains the parameters for DeleteResource.
type AuthorizationDeleteResourceParams struct {
	// CascadeDelete is if true, deletes all descendant resources and role assignments. If not set and the resource has children or assignments, the request will fail.
	// Defaults to false.
	CascadeDelete *bool `url:"cascade_delete,omitempty" json:"-"`
}

// DeleteResource delete an authorization resource
// Delete an authorization resource and all its descendants.
func (s *authorizationService) DeleteResource(ctx context.Context, resourceID string, params *AuthorizationDeleteResourceParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/authorization/resources/%s", resourceID), params, nil, nil, opts)
	return err
}

// AuthorizationListMembershipsForResourceParams contains the parameters for ListMembershipsForResource.
type AuthorizationListMembershipsForResourceParams struct {
	PaginationParams
	// PermissionSlug is the permission slug to filter by. Only users with this permission on the resource are returned.
	PermissionSlug string `url:"permission_slug" json:"-"`
	// Assignment is filter by assignment type. Use `direct` for direct assignments only, or `indirect` to include inherited assignments.
	Assignment *AuthorizationAssignment `url:"assignment,omitempty" json:"-"`
}

// ListMembershipsForResource list organization memberships for resource
// Returns all organization memberships that have a specific permission on a resource instance. This is useful for answering "Who can access this resource?".
func (s *authorizationService) ListMembershipsForResource(ctx context.Context, resourceID string, params *AuthorizationListMembershipsForResourceParams, opts ...RequestOption) *Iterator[UserOrganizationMembershipBaseListData] {
	return newIterator[UserOrganizationMembershipBaseListData](ctx, s.client, "GET", fmt.Sprintf("/authorization/resources/%s/organization_memberships", resourceID), params, "after", "data", opts)
}

// ListRoles list environment roles
// List all environment roles in priority order.
func (s *authorizationService) ListRoles(ctx context.Context, opts ...RequestOption) (*RoleList, error) {
	var result RoleList
	_, err := s.client.request(ctx, "GET", "/authorization/roles", nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationCreateRolesParams contains the parameters for CreateRoles.
type AuthorizationCreateRolesParams struct {
	// Slug is a unique slug for the role.
	Slug string `json:"slug"`
	// Name is a descriptive name for the role.
	Name string `json:"name"`
	// Description is an optional description of the role.
	Description *string `json:"description,omitempty"`
	// ResourceTypeSlug is the slug of the resource type the role is scoped to.
	ResourceTypeSlug *string `json:"resource_type_slug,omitempty"`
}

// CreateRoles create an environment role
// Create a new environment role.
func (s *authorizationService) CreateRoles(ctx context.Context, params *AuthorizationCreateRolesParams, opts ...RequestOption) (*Role, error) {
	var result Role
	_, err := s.client.request(ctx, "POST", "/authorization/roles", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetRole get an environment role
// Get an environment role by its slug.
func (s *authorizationService) GetRole(ctx context.Context, slug string, opts ...RequestOption) (*Role, error) {
	var result Role
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/authorization/roles/%s", slug), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationUpdateRoleParams contains the parameters for UpdateRole.
type AuthorizationUpdateRoleParams struct {
	// Name is a descriptive name for the role.
	Name *string `json:"name,omitempty"`
	// Description is an optional description of the role.
	Description *string `json:"description,omitempty"`
}

// UpdateRole update an environment role
// Update an existing environment role.
func (s *authorizationService) UpdateRole(ctx context.Context, slug string, params *AuthorizationUpdateRoleParams, opts ...RequestOption) (*Role, error) {
	var result Role
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/authorization/roles/%s", slug), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationAddRolePermissionParams contains the parameters for AddRolePermission.
type AuthorizationAddRolePermissionParams struct {
	// Slug is the slug of the permission to add to the role.
	Slug string `json:"slug"`
}

// AddRolePermission add a permission to an environment role
// Add a single permission to an environment role. If the permission is already assigned to the role, this operation has no effect.
func (s *authorizationService) AddRolePermission(ctx context.Context, slug string, params *AuthorizationAddRolePermissionParams, opts ...RequestOption) (*Role, error) {
	var result Role
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/authorization/roles/%s/permissions", slug), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationSetRolePermissionsParams contains the parameters for SetRolePermissions.
type AuthorizationSetRolePermissionsParams struct {
	// Permissions is the permission slugs to assign to the role.
	Permissions []string `json:"permissions"`
}

// SetRolePermissions set permissions for an environment role
// Replace all permissions on an environment role with the provided list.
func (s *authorizationService) SetRolePermissions(ctx context.Context, slug string, params *AuthorizationSetRolePermissionsParams, opts ...RequestOption) (*Role, error) {
	var result Role
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/authorization/roles/%s/permissions", slug), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationListPermissionsParams contains the parameters for ListPermissions.
type AuthorizationListPermissionsParams struct {
	PaginationParams
}

// ListPermissions list permissions
// Get a list of all permissions in your WorkOS environment.
func (s *authorizationService) ListPermissions(ctx context.Context, params *AuthorizationListPermissionsParams, opts ...RequestOption) *Iterator[AuthorizationPermission] {
	return newIterator[AuthorizationPermission](ctx, s.client, "GET", "/authorization/permissions", params, "after", "data", opts)
}

// AuthorizationCreatePermissionsParams contains the parameters for CreatePermissions.
type AuthorizationCreatePermissionsParams struct {
	// Slug is a unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
	Slug string `json:"slug"`
	// Name is a descriptive name for the Permission.
	Name string `json:"name"`
	// Description is an optional description of the Permission.
	Description *string `json:"description,omitempty"`
	// ResourceTypeSlug is the slug of the resource type this permission is scoped to.
	ResourceTypeSlug *string `json:"resource_type_slug,omitempty"`
}

// CreatePermissions create a permission
// Create a new permission in your WorkOS environment. The permission can then be assigned to environment roles and organization roles.
func (s *authorizationService) CreatePermissions(ctx context.Context, params *AuthorizationCreatePermissionsParams, opts ...RequestOption) (*Permission, error) {
	var result Permission
	_, err := s.client.request(ctx, "POST", "/authorization/permissions", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetPermission get a permission
// Retrieve a permission by its unique slug.
func (s *authorizationService) GetPermission(ctx context.Context, slug string, opts ...RequestOption) (*AuthorizationPermission, error) {
	var result AuthorizationPermission
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/authorization/permissions/%s", slug), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthorizationUpdatePermissionParams contains the parameters for UpdatePermission.
type AuthorizationUpdatePermissionParams struct {
	// Name is a descriptive name for the Permission.
	Name *string `json:"name,omitempty"`
	// Description is an optional description of the Permission.
	Description *string `json:"description,omitempty"`
}

// UpdatePermission update a permission
// Update an existing permission. Only the fields provided in the request body will be updated.
func (s *authorizationService) UpdatePermission(ctx context.Context, slug string, params *AuthorizationUpdatePermissionParams, opts ...RequestOption) (*AuthorizationPermission, error) {
	var result AuthorizationPermission
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/authorization/permissions/%s", slug), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeletePermission delete a permission
// Delete an existing permission. System permissions cannot be deleted.
func (s *authorizationService) DeletePermission(ctx context.Context, slug string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/authorization/permissions/%s", slug), nil, nil, nil, opts)
	return err
}
