// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
)

// ClientAPIService handles ClientApi operations.
type ClientAPIService struct {
	client *Client
}

// ClientAPICreateTokenParams contains the parameters for CreateToken.
type ClientAPICreateTokenParams struct {
	// OrganizationID is the ID of the organization to scope the Client API token to.
	OrganizationID string `json:"organization_id" url:"-"`
	// UserID is the ID of the user to issue the Client API token for.
	UserID string `json:"user_id" url:"-"`
}

// CreateToken generate a Client API token
// Generate a short-lived, session-bound token for the Client GraphQL API, scoped to an organization and user.
func (s *ClientAPIService) CreateToken(ctx context.Context, params *ClientAPICreateTokenParams, opts ...RequestOption) (*ClientAPITokenResponse, error) {
	var result ClientAPITokenResponse
	_, err := s.client.request(ctx, "POST", "/client/token", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
