// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// connectService handles Connect operations.
type connectService struct {
	client *Client
}

// ConnectCompleteOAuth2Params contains the parameters for CompleteOAuth2.
type ConnectCompleteOAuth2Params struct {
	ExternalAuthID string `json:"external_auth_id"`
	User *UserObject `json:"user"`
	UserConsentOptions []*UserConsentOption `json:"user_consent_options,omitempty"`
}

// CompleteOAuth2 complete external authentication
// Completes an external authentication flow and returns control to AuthKit. This endpoint is used with [Standalone Connect](https://workos.com/docs/authkit/connect/standalone) to bridge your existing authentication system with the Connect OAuth API infrastructure.
// After successfully authenticating a user in your application, calling this endpoint will:
// - Create or update the user in AuthKit, using the given `id` as its `external_id`.
// - Return a `redirect_uri` your application should redirect to in order for AuthKit to complete the flow
// Users are automatically created or updated based on the `id` and `email` provided. If a user with the same `id` exists, their information is updated. Otherwise, a new user is created.
// If you provide a new `id` with an `email` that already belongs to an existing user, the request will fail with an error as email addresses are unique to a user.
func (s *connectService) CompleteOAuth2(ctx context.Context, params *ConnectCompleteOAuth2Params, opts ...RequestOption) (*ExternalAuthCompleteResponse, error) {
	var result ExternalAuthCompleteResponse
	_, err := s.client.request(ctx, "POST", "/authkit/oauth2/complete", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ConnectListApplicationsParams contains the parameters for ListApplications.
type ConnectListApplicationsParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *ApplicationsOrder `url:"order,omitempty"`
	OrganizationID *string `url:"organization_id,omitempty"`
}

// ListApplications list Connect Applications
// List all Connect Applications in the current environment with optional filtering.
func (s *connectService) ListApplications(ctx context.Context, params *ConnectListApplicationsParams, opts ...RequestOption) *Iterator[ConnectApplication] {
	return newIterator[ConnectApplication](ctx, s.client, "GET", "/connect/applications", params, "data", opts)
}

// ConnectCreateApplicationsParams contains the parameters for CreateApplications.
type ConnectCreateApplicationsParams struct {
	Body interface{} `json:"-"`
}

// CreateApplications create a Connect Application
// Create a new Connect Application. Supports both OAuth and Machine-to-Machine (M2M) application types.
func (s *connectService) CreateApplications(ctx context.Context, params *ConnectCreateApplicationsParams, opts ...RequestOption) (*ConnectApplication, error) {
	var result ConnectApplication
	_, err := s.client.request(ctx, "POST", "/connect/applications", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetApplication get a Connect Application
// Retrieve details for a specific Connect Application by ID or client ID.
func (s *connectService) GetApplication(ctx context.Context, iD string, opts ...RequestOption) (*ConnectApplication, error) {
	var result ConnectApplication
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/connect/applications/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ConnectUpdateApplicationParams contains the parameters for UpdateApplication.
type ConnectUpdateApplicationParams struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Scopes *[]string `json:"scopes,omitempty"`
	RedirectUris *[]*RedirectUriDto `json:"redirect_uris,omitempty"`
}

// UpdateApplication update a Connect Application
// Update an existing Connect Application. For OAuth applications, you can update redirect URIs. For all applications, you can update the name, description, and scopes.
func (s *connectService) UpdateApplication(ctx context.Context, iD string, params *ConnectUpdateApplicationParams, opts ...RequestOption) (*ConnectApplication, error) {
	var result ConnectApplication
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/connect/applications/%s", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteApplication delete a Connect Application
// Delete an existing Connect Application.
func (s *connectService) DeleteApplication(ctx context.Context, iD string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/connect/applications/%s", iD), nil, nil, opts)
	return err
}

// ListApplicationClientSecrets list Client Secrets for a Connect Application
// List all client secrets associated with a Connect Application.
func (s *connectService) ListApplicationClientSecrets(ctx context.Context, iD string, opts ...RequestOption) (*ApplicationCredentialsListItem, error) {
	var result ApplicationCredentialsListItem
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/connect/applications/%s/client_secrets", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ConnectCreateApplicationClientSecretsParams contains the parameters for CreateApplicationClientSecrets.
type ConnectCreateApplicationClientSecretsParams struct {
}

// CreateApplicationClientSecrets create a new client secret for a Connect Application
// Create new secrets for a Connect Application.
func (s *connectService) CreateApplicationClientSecrets(ctx context.Context, iD string, params *ConnectCreateApplicationClientSecretsParams, opts ...RequestOption) (*NewConnectApplicationSecret, error) {
	var result NewConnectApplicationSecret
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/connect/applications/%s/client_secrets", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteClientSecret delete a Client Secret
// Delete (revoke) an existing client secret.
func (s *connectService) DeleteClientSecret(ctx context.Context, iD string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/connect/client_secrets/%s", iD), nil, nil, opts)
	return err
}
