// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// directorySyncService handles DirectorySync operations.
type directorySyncService struct {
	client *Client
}

// DirectorySyncListDirectoriesParams contains the parameters for ListDirectories.
type DirectorySyncListDirectoriesParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *DirectoriesOrder `url:"order,omitempty"`
	OrganizationID *string `url:"organization_id,omitempty"`
	Search *string `url:"search,omitempty"`
	Domain *string `url:"domain,omitempty"`
}

// ListDirectories list Directories
// Get a list of all of your existing directories matching the criteria specified.
func (s *directorySyncService) ListDirectories(ctx context.Context, params *DirectorySyncListDirectoriesParams, opts ...RequestOption) *Iterator[Directory] {
	return newIterator[Directory](ctx, s.client, "GET", "/directories", params, "data", opts)
}

// GetDirectory get a Directory
// Get the details of an existing directory.
func (s *directorySyncService) GetDirectory(ctx context.Context, iD string, opts ...RequestOption) (*Directory, error) {
	var result Directory
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/directories/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteDirectory delete a Directory
// Permanently deletes an existing directory. It cannot be undone.
func (s *directorySyncService) DeleteDirectory(ctx context.Context, iD string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/directories/%s", iD), nil, nil, opts)
	return err
}

// DirectorySyncListDirectoryGroupsParams contains the parameters for ListDirectoryGroups.
type DirectorySyncListDirectoryGroupsParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *DirectoryGroupsOrder `url:"order,omitempty"`
	Directory *string `url:"directory,omitempty"`
	User *string `url:"user,omitempty"`
}

// ListDirectoryGroups list Directory Groups
// Get a list of all of existing directory groups matching the criteria specified.
func (s *directorySyncService) ListDirectoryGroups(ctx context.Context, params *DirectorySyncListDirectoryGroupsParams, opts ...RequestOption) *Iterator[DirectoryGroup] {
	return newIterator[DirectoryGroup](ctx, s.client, "GET", "/directory_groups", params, "data", opts)
}

// GetDirectoryGroup get a Directory Group
// Get the details of an existing Directory Group.
func (s *directorySyncService) GetDirectoryGroup(ctx context.Context, iD string, opts ...RequestOption) (*DirectoryGroup, error) {
	var result DirectoryGroup
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/directory_groups/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DirectorySyncListDirectoryUsersParams contains the parameters for ListDirectoryUsers.
type DirectorySyncListDirectoryUsersParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *DirectoryUsersOrder `url:"order,omitempty"`
	Directory *string `url:"directory,omitempty"`
	Group *string `url:"group,omitempty"`
}

// ListDirectoryUsers list Directory Users
// Get a list of all of existing Directory Users matching the criteria specified.
func (s *directorySyncService) ListDirectoryUsers(ctx context.Context, params *DirectorySyncListDirectoryUsersParams, opts ...RequestOption) *Iterator[DirectoryUserWithGroups] {
	return newIterator[DirectoryUserWithGroups](ctx, s.client, "GET", "/directory_users", params, "data", opts)
}

// GetDirectoryUser get a Directory User
// Get the details of an existing Directory User.
func (s *directorySyncService) GetDirectoryUser(ctx context.Context, iD string, opts ...RequestOption) (*DirectoryUserWithGroups, error) {
	var result DirectoryUserWithGroups
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/directory_users/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
