// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
)

// eventService handles Events operations.
type eventService struct {
	client *Client
}

// EventsListParams contains the parameters for List.
type EventsListParams struct {
	Before         *string      `url:"before,omitempty" json:"-"`
	After          *string      `url:"after,omitempty" json:"-"`
	Limit          *int         `url:"limit,omitempty" json:"-"`
	Order          *EventsOrder `url:"order,omitempty" json:"-"`
	Events         []string     `url:"events,omitempty" json:"-"`
	RangeStart     *string      `url:"range_start,omitempty" json:"-"`
	RangeEnd       *string      `url:"range_end,omitempty" json:"-"`
	OrganizationID *string      `url:"organization_id,omitempty" json:"-"`
}

// List listEvents
// List events for the current environment.
func (s *eventService) List(ctx context.Context, params *EventsListParams, opts ...RequestOption) *Iterator[EventSchema] {
	return newIterator[EventSchema](ctx, s.client, "GET", "/events", params, "after", "data", opts)
}
