// Code generated by oagen. DO NOT EDIT.

package workos_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/workos/workos-go/v8"
)

func TestGroups_ListOrganizationGroups(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/organizations/test_organizationId/groups", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_group.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Groups().ListOrganizationGroups(context.Background(), "test_organizationId", &workos.GroupsListOrganizationGroupsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestGroups_ListOrganizationGroups_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Groups().ListOrganizationGroups(context.Background(), "test_organizationId", &workos.GroupsListOrganizationGroupsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestGroups_CreateOrganizationGroup(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/organizations/test_organizationId/groups", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/group.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Groups().CreateOrganizationGroup(context.Background(), "test_organizationId", &workos.GroupsCreateOrganizationGroupParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "group_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "org_01EHWNCE74X7JSDV0X3SZ3KJNY", result.OrganizationID)
	require.Equal(t, "Engineering", result.Name)
}

func TestGroups_GetOrganizationGroup(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/organizations/test_organizationId/groups/test_groupId", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/group.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Groups().GetOrganizationGroup(context.Background(), "test_organizationId", "test_groupId")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "group_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "org_01EHWNCE74X7JSDV0X3SZ3KJNY", result.OrganizationID)
	require.Equal(t, "Engineering", result.Name)
}

func TestGroups_UpdateOrganizationGroup(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		require.Equal(t, "/organizations/test_organizationId/groups/test_groupId", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/group.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Groups().UpdateOrganizationGroup(context.Background(), "test_organizationId", "test_groupId", &workos.GroupsUpdateOrganizationGroupParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "group_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "org_01EHWNCE74X7JSDV0X3SZ3KJNY", result.OrganizationID)
	require.Equal(t, "Engineering", result.Name)
}

func TestGroups_DeleteOrganizationGroup(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/organizations/test_organizationId/groups/test_groupId", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Groups().DeleteOrganizationGroup(context.Background(), "test_organizationId", "test_groupId")
	require.NoError(t, err)
}

func TestGroups_ListOrganizationMemberships(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/organizations/test_organizationId/groups/test_groupId/organization-memberships", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_user_organization_membership_base_list_data.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Groups().ListOrganizationMemberships(context.Background(), "test_organizationId", "test_groupId", &workos.GroupsListOrganizationMembershipsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestGroups_ListOrganizationMemberships_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Groups().ListOrganizationMemberships(context.Background(), "test_organizationId", "test_groupId", &workos.GroupsListOrganizationMembershipsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestGroups_CreateOrganizationMembership(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/organizations/test_organizationId/groups/test_groupId/organization-memberships", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/group.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Groups().CreateOrganizationMembership(context.Background(), "test_organizationId", "test_groupId", &workos.GroupsCreateOrganizationMembershipParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "group_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "org_01EHWNCE74X7JSDV0X3SZ3KJNY", result.OrganizationID)
	require.Equal(t, "Engineering", result.Name)
}

func TestGroups_DeleteOrganizationMembership(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/organizations/test_organizationId/groups/test_groupId/organization-memberships/test_omId", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Groups().DeleteOrganizationMembership(context.Background(), "test_organizationId", "test_groupId", "test_omId")
	require.NoError(t, err)
}

func TestGroups_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Groups().ListOrganizationGroups(context.Background(), "test_organizationId", &workos.GroupsListOrganizationGroupsParams{})
	require.False(t, iter.Next())
	require.IsType(t, &workos.AuthenticationError{}, iter.Err())
}

func TestGroups_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Groups().ListOrganizationGroups(context.Background(), "test_organizationId", &workos.GroupsListOrganizationGroupsParams{})
	require.False(t, iter.Next())
	require.IsType(t, &workos.NotFoundError{}, iter.Err())
}

func TestGroups_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Groups().ListOrganizationGroups(context.Background(), "test_organizationId", &workos.GroupsListOrganizationGroupsParams{})
	require.False(t, iter.Next())
	require.IsType(t, &workos.UnprocessableEntityError{}, iter.Err())
}
