// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
)

// GroupService handles Groups operations.
type GroupService struct {
	client *Client
}

// GroupsListOrganizationGroupsParams contains the parameters for ListOrganizationGroups.
type GroupsListOrganizationGroupsParams struct {
	PaginationParams
}

// ListOrganizationGroups list groups
// Get a paginated list of groups within an organization.
func (s *GroupService) ListOrganizationGroups(ctx context.Context, organizationID string, params *GroupsListOrganizationGroupsParams, opts ...RequestOption) *Iterator[Group] {
	return newIterator[Group](ctx, s.client, "GET", fmt.Sprintf("/organizations/%s/groups", url.PathEscape(organizationID)), params, "after", "data", opts, map[string]string{"limit": "10", "order": "desc"})
}

// GroupsCreateOrganizationGroupParams contains the parameters for CreateOrganizationGroup.
type GroupsCreateOrganizationGroupParams struct {
	// Name is the name of the Group.
	Name string `json:"name" url:"-"`
	// Description is an optional description of the Group.
	Description *string `json:"description,omitempty" url:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for GroupsCreateOrganizationGroupParams.
func (p GroupsCreateOrganizationGroupParams) MarshalJSON() ([]byte, error) {
	type Alias GroupsCreateOrganizationGroupParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if len(p.NullFields) == 0 {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	nullable := map[string]bool{
		"description": true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("GroupsCreateOrganizationGroupParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// CreateOrganizationGroup create a group
// Create a new group within an organization.
func (s *GroupService) CreateOrganizationGroup(ctx context.Context, organizationID string, params *GroupsCreateOrganizationGroupParams, opts ...RequestOption) (*Group, error) {
	var result Group
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/organizations/%s/groups", url.PathEscape(organizationID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOrganizationGroup get a group
// Retrieve a group by its ID within an organization.
func (s *GroupService) GetOrganizationGroup(ctx context.Context, organizationID string, groupID string, opts ...RequestOption) (*Group, error) {
	var result Group
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/organizations/%s/groups/%s", url.PathEscape(organizationID), url.PathEscape(groupID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GroupsUpdateOrganizationGroupParams contains the parameters for UpdateOrganizationGroup.
type GroupsUpdateOrganizationGroupParams struct {
	// Name is the name of the Group.
	Name *string `json:"name,omitempty" url:"-"`
	// Description is an optional description of the Group.
	Description *string `json:"description,omitempty" url:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for GroupsUpdateOrganizationGroupParams.
func (p GroupsUpdateOrganizationGroupParams) MarshalJSON() ([]byte, error) {
	type Alias GroupsUpdateOrganizationGroupParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if len(p.NullFields) == 0 {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	nullable := map[string]bool{
		"description": true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("GroupsUpdateOrganizationGroupParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// UpdateOrganizationGroup update a group
// Update an existing group. Only the fields provided in the request body will be updated.
func (s *GroupService) UpdateOrganizationGroup(ctx context.Context, organizationID string, groupID string, params *GroupsUpdateOrganizationGroupParams, opts ...RequestOption) (*Group, error) {
	var result Group
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/organizations/%s/groups/%s", url.PathEscape(organizationID), url.PathEscape(groupID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteOrganizationGroup delete a group
// Delete a group from an organization.
func (s *GroupService) DeleteOrganizationGroup(ctx context.Context, organizationID string, groupID string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/organizations/%s/groups/%s", url.PathEscape(organizationID), url.PathEscape(groupID)), nil, nil, nil, opts)
	return err
}

// GroupsListOrganizationMembershipsParams contains the parameters for ListOrganizationMemberships.
type GroupsListOrganizationMembershipsParams struct {
	PaginationParams
}

// ListOrganizationMemberships list Group members
// Get a list of organization memberships in a group.
func (s *GroupService) ListOrganizationMemberships(ctx context.Context, organizationID string, groupID string, params *GroupsListOrganizationMembershipsParams, opts ...RequestOption) *Iterator[UserOrganizationMembershipBaseListData] {
	return newIterator[UserOrganizationMembershipBaseListData](ctx, s.client, "GET", fmt.Sprintf("/organizations/%s/groups/%s/organization-memberships", url.PathEscape(organizationID), url.PathEscape(groupID)), params, "after", "data", opts, map[string]string{"limit": "10", "order": "desc"})
}

// GroupsCreateOrganizationMembershipParams contains the parameters for CreateOrganizationMembership.
type GroupsCreateOrganizationMembershipParams struct {
	// OrganizationMembershipID is the ID of the Organization Membership to add to the group.
	OrganizationMembershipID string `json:"organization_membership_id" url:"-"`
}

// CreateOrganizationMembership add a member to a Group
// Add an organization membership to a group.
func (s *GroupService) CreateOrganizationMembership(ctx context.Context, organizationID string, groupID string, params *GroupsCreateOrganizationMembershipParams, opts ...RequestOption) (*Group, error) {
	var result Group
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/organizations/%s/groups/%s/organization-memberships", url.PathEscape(organizationID), url.PathEscape(groupID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteOrganizationMembership remove a member from a Group
// Remove an organization membership from a group.
func (s *GroupService) DeleteOrganizationMembership(ctx context.Context, organizationID string, groupID string, omID string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/organizations/%s/groups/%s/organization-memberships/%s", url.PathEscape(organizationID), url.PathEscape(groupID), url.PathEscape(omID)), nil, nil, nil, opts)
	return err
}
