// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// multiFactorAuthService handles MultiFactorAuth operations.
type multiFactorAuthService struct {
	client *Client
}

// MultiFactorAuthVerifyChallengeParams contains the parameters for VerifyChallenge.
type MultiFactorAuthVerifyChallengeParams struct {
	Code string `json:"code"`
}

// VerifyChallenge verify Challenge
// Verifies an Authentication Challenge.
func (s *multiFactorAuthService) VerifyChallenge(ctx context.Context, iD string, params *MultiFactorAuthVerifyChallengeParams, opts ...RequestOption) (*AuthenticationChallengeVerifyResponse, error) {
	var result AuthenticationChallengeVerifyResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/auth/challenges/%s/verify", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// MultiFactorAuthEnrollFactorParams contains the parameters for EnrollFactor.
type MultiFactorAuthEnrollFactorParams struct {
	Type AuthenticationFactorsCreateRequestType `json:"type"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	TotpIssuer *string `json:"totp_issuer,omitempty"`
	TotpUser *string `json:"totp_user,omitempty"`
	UserID *string `json:"user_id,omitempty"`
}

// EnrollFactor enroll Factor
// Enrolls an Authentication Factor to be used as an additional factor of authentication. The returned ID should be used to create an authentication Challenge.
func (s *multiFactorAuthService) EnrollFactor(ctx context.Context, params *MultiFactorAuthEnrollFactorParams, opts ...RequestOption) (*AuthenticationFactorEnrolled, error) {
	var result AuthenticationFactorEnrolled
	_, err := s.client.request(ctx, "POST", "/auth/factors/enroll", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetFactor get Factor
// Gets an Authentication Factor.
func (s *multiFactorAuthService) GetFactor(ctx context.Context, iD string, opts ...RequestOption) (*AuthenticationFactor, error) {
	var result AuthenticationFactor
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/auth/factors/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteFactor delete Factor
// Permanently deletes an Authentication Factor. It cannot be undone.
func (s *multiFactorAuthService) DeleteFactor(ctx context.Context, iD string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/auth/factors/%s", iD), nil, nil, opts)
	return err
}

// MultiFactorAuthChallengeFactorParams contains the parameters for ChallengeFactor.
type MultiFactorAuthChallengeFactorParams struct {
	SmsTemplate *string `json:"sms_template,omitempty"`
}

// ChallengeFactor challenge Factor
// Creates a Challenge for an Authentication Factor.
func (s *multiFactorAuthService) ChallengeFactor(ctx context.Context, iD string, params *MultiFactorAuthChallengeFactorParams, opts ...RequestOption) (*AuthenticationChallenge, error) {
	var result AuthenticationChallenge
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/auth/factors/%s/challenge", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// MultiFactorAuthListUserAuthFactorsParams contains the parameters for ListUserAuthFactors.
type MultiFactorAuthListUserAuthFactorsParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *UserManagementMultiFactorAuthenticationOrder `url:"order,omitempty"`
}

// ListUserAuthFactors list authentication factors
// Lists the [authentication factors](https://workos.com/docs/reference/authkit/mfa/authentication-factor) for a user.
func (s *multiFactorAuthService) ListUserAuthFactors(ctx context.Context, userlandUserID string, params *MultiFactorAuthListUserAuthFactorsParams, opts ...RequestOption) *Iterator[AuthenticationFactor] {
	return newIterator[AuthenticationFactor](ctx, s.client, "GET", fmt.Sprintf("/user_management/users/%s/auth_factors", userlandUserID), params, "data", opts)
}

// MultiFactorAuthCreateUserAuthFactorsParams contains the parameters for CreateUserAuthFactors.
type MultiFactorAuthCreateUserAuthFactorsParams struct {
	Type string `json:"type"`
	TotpIssuer *string `json:"totp_issuer,omitempty"`
	TotpUser *string `json:"totp_user,omitempty"`
	TotpSecret *string `json:"totp_secret,omitempty"`
}

// CreateUserAuthFactors enroll an authentication factor
// Enrolls a user in a new [authentication factor](https://workos.com/docs/reference/authkit/mfa/authentication-factor).
func (s *multiFactorAuthService) CreateUserAuthFactors(ctx context.Context, userlandUserID string, params *MultiFactorAuthCreateUserAuthFactorsParams, opts ...RequestOption) (*UserAuthenticationFactorEnrollResponse, error) {
	var result UserAuthenticationFactorEnrollResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/user_management/users/%s/auth_factors", userlandUserID), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
