// Code generated by oagen. DO NOT EDIT.

package workos_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/workos/workos-go/v10"
)

func TestOrganizationsDataProviders_GetConnectedAccount(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/organizations/test_organization_id/connected_accounts/test_slug", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/connected_account.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationsDataProviders().GetConnectedAccount(context.Background(), "test_organization_id", "test_slug", &workos.OrganizationsDataProvidersGetConnectedAccountParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "data_installation_01EHZNVPK3SFK441A1RGBFSHRT", result.ID)
	require.Equal(t, "2024-01-16T14:20:00.000Z", result.CreatedAt)
	require.Equal(t, "2024-01-16T14:20:00.000Z", result.UpdatedAt)
}

func TestOrganizationsDataProviders_CreateConnectedAccount(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/organizations/test_organization_id/connected_accounts/test_slug", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/connected_account.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationsDataProviders().CreateConnectedAccount(context.Background(), "test_organization_id", "test_slug", &workos.OrganizationsDataProvidersCreateConnectedAccountParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "data_installation_01EHZNVPK3SFK441A1RGBFSHRT", result.ID)
	require.Equal(t, "2024-01-16T14:20:00.000Z", result.CreatedAt)
	require.Equal(t, "2024-01-16T14:20:00.000Z", result.UpdatedAt)
}

func TestOrganizationsDataProviders_UpdateConnectedAccount(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/organizations/test_organization_id/connected_accounts/test_slug", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/connected_account.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationsDataProviders().UpdateConnectedAccount(context.Background(), "test_organization_id", "test_slug", &workos.OrganizationsDataProvidersUpdateConnectedAccountParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "data_installation_01EHZNVPK3SFK441A1RGBFSHRT", result.ID)
	require.Equal(t, "2024-01-16T14:20:00.000Z", result.CreatedAt)
	require.Equal(t, "2024-01-16T14:20:00.000Z", result.UpdatedAt)
}

func TestOrganizationsDataProviders_DeleteConnectedAccount(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/organizations/test_organization_id/connected_accounts/test_slug", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.OrganizationsDataProviders().DeleteConnectedAccount(context.Background(), "test_organization_id", "test_slug", &workos.OrganizationsDataProvidersDeleteConnectedAccountParams{})
	require.NoError(t, err)
}

func TestOrganizationsDataProviders_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/organizations/test_organization_id/data_providers", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/data_integrations_list_response.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationsDataProviders().List(context.Background(), "test_organization_id", &workos.OrganizationsDataProvidersListParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestOrganizationsDataProviders_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.OrganizationsDataProviders().GetConnectedAccount(context.Background(), "test_organization_id", "test_slug", &workos.OrganizationsDataProvidersGetConnectedAccountParams{})
	require.IsType(t, &workos.AuthenticationError{}, err)
}

func TestOrganizationsDataProviders_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.OrganizationsDataProviders().GetConnectedAccount(context.Background(), "test_organization_id", "test_slug", &workos.OrganizationsDataProvidersGetConnectedAccountParams{})
	require.IsType(t, &workos.NotFoundError{}, err)
}

func TestOrganizationsDataProviders_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.OrganizationsDataProviders().GetConnectedAccount(context.Background(), "test_organization_id", "test_slug", &workos.OrganizationsDataProvidersGetConnectedAccountParams{})
	require.IsType(t, &workos.UnprocessableEntityError{}, err)
}
