// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// organizationService handles Organizations operations.
type organizationService struct {
	client *Client
}

// OrganizationsListParams contains the parameters for List.
type OrganizationsListParams struct {
	Before  *string             `url:"before,omitempty" json:"-"`
	After   *string             `url:"after,omitempty" json:"-"`
	Limit   *int                `url:"limit,omitempty" json:"-"`
	Order   *OrganizationsOrder `url:"order,omitempty" json:"-"`
	Domains []string            `url:"domains,omitempty" json:"-"`
	Search  *string             `url:"search,omitempty" json:"-"`
}

// List listOrganizations
// Get a list of all of your existing organizations matching the criteria specified.
func (s *organizationService) List(ctx context.Context, params *OrganizationsListParams, opts ...RequestOption) *Iterator[Organization] {
	return newIterator[Organization](ctx, s.client, "GET", "/organizations", params, "after", "data", opts)
}

// OrganizationsCreateParams contains the parameters for Create.
type OrganizationsCreateParams struct {
	Name                             string                    `json:"name"`
	AllowProfilesOutsideOrganization *bool                     `json:"allow_profiles_outside_organization,omitempty"`
	Domains                          []string                  `json:"domains,omitempty"`
	DomainData                       []*OrganizationDomainData `json:"domain_data,omitempty"`
	Metadata                         *map[string]string        `json:"metadata,omitempty"`
	ExternalID                       *string                   `json:"external_id,omitempty"`
}

// Create createAnOrganization
// Creates a new organization in the current environment.
func (s *organizationService) Create(ctx context.Context, params *OrganizationsCreateParams, opts ...RequestOption) (*Organization, error) {
	var result Organization
	_, err := s.client.request(ctx, "POST", "/organizations", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetByExternalID getAnOrganizationByExternalID
// Get the details of an existing organization by an [external identifier](https://workos.com/docs/authkit/metadata/external-identifiers).
func (s *organizationService) GetByExternalID(ctx context.Context, externalID string, opts ...RequestOption) (*Organization, error) {
	var result Organization
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/organizations/external_id/%s", externalID), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get getAnOrganization
// Get the details of an existing organization.
func (s *organizationService) Get(ctx context.Context, id string, opts ...RequestOption) (*Organization, error) {
	var result Organization
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/organizations/%s", id), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// OrganizationsUpdateParams contains the parameters for Update.
type OrganizationsUpdateParams struct {
	Name                             *string                   `json:"name,omitempty"`
	AllowProfilesOutsideOrganization *bool                     `json:"allow_profiles_outside_organization,omitempty"`
	Domains                          []string                  `json:"domains,omitempty"`
	DomainData                       []*OrganizationDomainData `json:"domain_data,omitempty"`
	StripeCustomerID                 *string                   `json:"stripe_customer_id,omitempty"`
	Metadata                         *map[string]string        `json:"metadata,omitempty"`
	ExternalID                       *string                   `json:"external_id,omitempty"`
}

// Update updateAnOrganization
// Updates an organization in the current environment.
func (s *organizationService) Update(ctx context.Context, id string, params *OrganizationsUpdateParams, opts ...RequestOption) (*Organization, error) {
	var result Organization
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/organizations/%s", id), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete deleteAnOrganization
// Permanently deletes an organization in the current environment. It cannot be undone.
func (s *organizationService) Delete(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/organizations/%s", id), nil, nil, nil, opts)
	return err
}

// ListAuditLogConfiguration getAuditLogConfiguration
// Get the unified view of audit log trail and stream configuration for an organization.
func (s *organizationService) ListAuditLogConfiguration(ctx context.Context, id string, opts ...RequestOption) (*AuditLogConfiguration, error) {
	var result AuditLogConfiguration
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/organizations/%s/audit_log_configuration", id), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
