// Code generated by oagen. DO NOT EDIT.

package workos_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/workos/workos-go/v9"
)

func TestOrganizationMembership_List(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/user_management/organization_memberships", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_user_organization_membership.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.OrganizationMembership().List(context.Background(), &workos.OrganizationMembershipListParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestOrganizationMembership_List_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.OrganizationMembership().List(context.Background(), &workos.OrganizationMembershipListParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestOrganizationMembership_Create(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		require.Equal(t, "/user_management/organization_memberships", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/organization_membership.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationMembership().Create(context.Background(), &workos.OrganizationMembershipCreateParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "om_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "user_01E4ZCR3C5A4QZ2Z2JQXGKZJ9E", result.UserID)
	require.Equal(t, "org_01E4ZCR3C56J083X43JQXF3JK5", result.OrganizationID)
}

func TestOrganizationMembership_Get(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/user_management/organization_memberships/test_id", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/user_organization_membership.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationMembership().Get(context.Background(), "test_id")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "om_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "user_01E4ZCR3C56J083X43JQXF3JK5", result.UserID)
	require.Equal(t, "org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationID)
}

func TestOrganizationMembership_Update(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/user_management/organization_memberships/test_id", r.URL.Path)
		body, _ := io.ReadAll(r.Body)
		var bodyMap map[string]interface{}
		require.NoError(t, json.Unmarshal(body, &bodyMap))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/user_organization_membership.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationMembership().Update(context.Background(), "test_id", &workos.OrganizationMembershipUpdateParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "om_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "user_01E4ZCR3C56J083X43JQXF3JK5", result.UserID)
	require.Equal(t, "org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationID)
}

func TestOrganizationMembership_Delete(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		require.Equal(t, "/user_management/organization_memberships/test_id", r.URL.Path)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.OrganizationMembership().Delete(context.Background(), "test_id")
	require.NoError(t, err)
}

func TestOrganizationMembership_Deactivate(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/user_management/organization_memberships/test_id/deactivate", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/organization_membership.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationMembership().Deactivate(context.Background(), "test_id")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "om_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "user_01E4ZCR3C5A4QZ2Z2JQXGKZJ9E", result.UserID)
	require.Equal(t, "org_01E4ZCR3C56J083X43JQXF3JK5", result.OrganizationID)
}

func TestOrganizationMembership_Reactivate(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PUT", r.Method)
		require.Equal(t, "/user_management/organization_memberships/test_id/reactivate", r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/user_organization_membership.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationMembership().Reactivate(context.Background(), "test_id")
	require.NoError(t, err)
	require.NotNil(t, result)
	require.Equal(t, "om_01HXYZ123456789ABCDEFGHIJ", result.ID)
	require.Equal(t, "user_01E4ZCR3C56J083X43JQXF3JK5", result.UserID)
	require.Equal(t, "org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationID)
}

func TestOrganizationMembership_ListGroups(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/user_management/organization_memberships/test_omId/groups", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_group.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.OrganizationMembership().ListGroups(context.Background(), "test_omId", &workos.OrganizationMembershipListGroupsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestOrganizationMembership_ListGroups_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.OrganizationMembership().ListGroups(context.Background(), "test_omId", &workos.OrganizationMembershipListGroupsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestOrganizationMembership_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.OrganizationMembership().List(context.Background(), &workos.OrganizationMembershipListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &workos.AuthenticationError{}, iter.Err())
}

func TestOrganizationMembership_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.OrganizationMembership().List(context.Background(), &workos.OrganizationMembershipListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &workos.NotFoundError{}, iter.Err())
}

func TestOrganizationMembership_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.OrganizationMembership().List(context.Background(), &workos.OrganizationMembershipListParams{})
	require.False(t, iter.Next())
	require.IsType(t, &workos.UnprocessableEntityError{}, iter.Err())
}
