// Code generated by oagen. DO NOT EDIT.

package workos_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/workos/workos-go/v6"
)

func TestOrganizationDomains_Create(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, _ := os.ReadFile("testdata/organization_domain.json")
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationDomains().Create(context.Background(), &workos.OrganizationDomainsCreateParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestOrganizationDomains_Get(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, _ := os.ReadFile("testdata/organization_domain_stand_alone.json")
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationDomains().Get(context.Background(), "test_id")
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestOrganizationDomains_Delete(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.OrganizationDomains().Delete(context.Background(), "test_id")
	require.NoError(t, err)
}

func TestOrganizationDomains_Verify(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, _ := os.ReadFile("testdata/organization_domain_stand_alone.json")
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.OrganizationDomains().Verify(context.Background(), "test_id")
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestOrganizationDomains_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.OrganizationDomains().Create(context.Background(), &workos.OrganizationDomainsCreateParams{})
	require.IsType(t, &workos.AuthenticationError{}, err)
}
