// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// organizationDomainService handles OrganizationDomains operations.
type organizationDomainService struct {
	client *Client
}

// OrganizationDomainsCreateParams contains the parameters for Create.
type OrganizationDomainsCreateParams struct {
	// Domain is the domain to add to the organization.
	Domain string `json:"domain"`
	// OrganizationID is the ID of the organization to add the domain to.
	OrganizationID string `json:"organization_id"`
}

// Create create an Organization Domain
// Creates a new Organization Domain.
func (s *organizationDomainService) Create(ctx context.Context, params *OrganizationDomainsCreateParams, opts ...RequestOption) (*OrganizationDomain, error) {
	var result OrganizationDomain
	_, err := s.client.request(ctx, "POST", "/organization_domains", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get get an Organization Domain
// Get the details of an existing organization domain.
func (s *organizationDomainService) Get(ctx context.Context, id string, opts ...RequestOption) (*OrganizationDomainStandAlone, error) {
	var result OrganizationDomainStandAlone
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/organization_domains/%s", id), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete delete an Organization Domain
// Permanently deletes an organization domain. It cannot be undone.
func (s *organizationDomainService) Delete(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/organization_domains/%s", id), nil, nil, nil, opts)
	return err
}

// Verify verify an Organization Domain
// Initiates verification process for an Organization Domain.
func (s *organizationDomainService) Verify(ctx context.Context, id string, opts ...RequestOption) (*OrganizationDomainStandAlone, error) {
	var result OrganizationDomainStandAlone
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/organization_domains/%s/verify", id), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
