// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// organizationDomainsService handles OrganizationDomains operations.
type organizationDomainsService struct {
	client *Client
}

// OrganizationDomainsCreateOrganizationDomainsParams contains the parameters for CreateOrganizationDomains.
type OrganizationDomainsCreateOrganizationDomainsParams struct {
	Domain string `json:"domain"`
	OrganizationID string `json:"organization_id"`
}

// CreateOrganizationDomains create an Organization Domain
// Creates a new Organization Domain.
func (s *organizationDomainsService) CreateOrganizationDomains(ctx context.Context, params *OrganizationDomainsCreateOrganizationDomainsParams, opts ...RequestOption) (*OrganizationDomain, error) {
	var result OrganizationDomain
	_, err := s.client.request(ctx, "POST", "/organization_domains", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOrganizationDomain get an Organization Domain
// Get the details of an existing organization domain.
func (s *organizationDomainsService) GetOrganizationDomain(ctx context.Context, iD string, opts ...RequestOption) (*OrganizationDomainStandAlone, error) {
	var result OrganizationDomainStandAlone
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/organization_domains/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteOrganizationDomain delete an Organization Domain
// Permanently deletes an organization domain. It cannot be undone.
func (s *organizationDomainsService) DeleteOrganizationDomain(ctx context.Context, iD string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/organization_domains/%s", iD), nil, nil, opts)
	return err
}

// VerifyOrganizationDomain verify an Organization Domain
// Initiates verification process for an Organization Domain.
func (s *organizationDomainsService) VerifyOrganizationDomain(ctx context.Context, iD string, opts ...RequestOption) (*OrganizationDomainStandAlone, error) {
	var result OrganizationDomainStandAlone
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/organization_domains/%s/verify", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
