// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// pipesService handles Pipes operations.
type pipesService struct {
	client *Client
}

// PipesAuthorizeDataIntegrationParams contains the parameters for AuthorizeDataIntegration.
type PipesAuthorizeDataIntegrationParams struct {
	UserID string `json:"user_id"`
	OrganizationID *string `json:"organization_id,omitempty"`
	ReturnTo *string `json:"return_to,omitempty"`
}

// AuthorizeDataIntegration get authorization URL
// Generates an OAuth authorization URL to initiate the connection flow for a user. Redirect the user to the returned URL to begin the OAuth flow with the third-party provider.
func (s *pipesService) AuthorizeDataIntegration(ctx context.Context, slug string, params *PipesAuthorizeDataIntegrationParams, opts ...RequestOption) (*DataIntegrationAuthorizeURLResponse, error) {
	var result DataIntegrationAuthorizeURLResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/data-integrations/%s/authorize", slug), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// PipesCreateDataIntegrationTokenParams contains the parameters for CreateDataIntegrationToken.
type PipesCreateDataIntegrationTokenParams struct {
	UserID string `json:"user_id"`
	OrganizationID *string `json:"organization_id,omitempty"`
}

// CreateDataIntegrationToken get an access token for a connected account
// Fetches a valid OAuth access token for a user's connected account. WorkOS automatically handles token refresh, ensuring you always receive a valid, non-expired token.
func (s *pipesService) CreateDataIntegrationToken(ctx context.Context, slug string, params *PipesCreateDataIntegrationTokenParams, opts ...RequestOption) (*DataIntegrationAccessTokenResponse, error) {
	var result DataIntegrationAccessTokenResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/data-integrations/%s/token", slug), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// PipesGetUserConnectedAccountParams contains the parameters for GetUserConnectedAccount.
type PipesGetUserConnectedAccountParams struct {
	OrganizationID *string `url:"organization_id,omitempty"`
}

// GetUserConnectedAccount get a connected account
// Retrieves a user's [connected account](https://workos.com/docs/reference/pipes/connected-account) for a specific provider.
func (s *pipesService) GetUserConnectedAccount(ctx context.Context, userID string, slug string, params *PipesGetUserConnectedAccountParams, opts ...RequestOption) (*ConnectedAccount, error) {
	var result ConnectedAccount
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/users/%s/connected_accounts/%s", userID, slug), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// PipesDeleteUserConnectedAccountParams contains the parameters for DeleteUserConnectedAccount.
type PipesDeleteUserConnectedAccountParams struct {
	OrganizationID *string `url:"organization_id,omitempty"`
}

// DeleteUserConnectedAccount delete a connected account
// Disconnects WorkOS's account for the user, including removing any stored access and refresh tokens. The user will need to reauthorize if they want to reconnect. This does not revoke access on the provider side.
func (s *pipesService) DeleteUserConnectedAccount(ctx context.Context, userID string, slug string, params *PipesDeleteUserConnectedAccountParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/user_management/users/%s/connected_accounts/%s", userID, slug), params, nil, opts)
	return err
}

// PipesListUserDataProvidersParams contains the parameters for ListUserDataProviders.
type PipesListUserDataProvidersParams struct {
	OrganizationID *string `url:"organization_id,omitempty"`
}

// ListUserDataProviders list providers
// Retrieves a list of available providers and the user's connection status for each. Returns all providers configured for your environment, along with the user's [connected account](https://workos.com/docs/reference/pipes/connected-account) information where applicable.
func (s *pipesService) ListUserDataProviders(ctx context.Context, userID string, params *PipesListUserDataProvidersParams, opts ...RequestOption) (*DataIntegrationsListResponse, error) {
	var result DataIntegrationsListResponse
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/users/%s/data_providers", userID), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
