// Code generated by oagen. DO NOT EDIT.

package workos_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/workos/workos-go/v6"
)

func TestPipes_AuthorizeDataIntegration(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, _ := os.ReadFile("testdata/data_integration_authorize_url_response.json")
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Pipes().AuthorizeDataIntegration(context.Background(), "test_slug", &workos.PipesAuthorizeDataIntegrationParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestPipes_CreateDataIntegrationToken(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, _ := os.ReadFile("testdata/data_integration_access_token_response.json")
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Pipes().CreateDataIntegrationToken(context.Background(), "test_slug", &workos.PipesCreateDataIntegrationTokenParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestPipes_GetUserConnectedAccount(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, _ := os.ReadFile("testdata/connected_account.json")
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Pipes().GetUserConnectedAccount(context.Background(), "test_user_id", "test_slug", &workos.PipesGetUserConnectedAccountParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestPipes_DeleteUserConnectedAccount(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Pipes().DeleteUserConnectedAccount(context.Background(), "test_user_id", "test_slug", &workos.PipesDeleteUserConnectedAccountParams{})
	require.NoError(t, err)
}

func TestPipes_ListUserDataProviders(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, _ := os.ReadFile("testdata/data_integrations_list_response.json")
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Pipes().ListUserDataProviders(context.Background(), "test_user_id", &workos.PipesListUserDataProvidersParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestPipes_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	_, err := client.Pipes().AuthorizeDataIntegration(context.Background(), "test_slug", &workos.PipesAuthorizeDataIntegrationParams{})
	require.IsType(t, &workos.AuthenticationError{}, err)
}
