// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
	"net/url"
)

// PlatformTeamService handles PlatformTeams operations.
type PlatformTeamService struct {
	client *Client
}

// PlatformTeamsCreateTeamParams contains the parameters for CreateTeam.
type PlatformTeamsCreateTeamParams struct {
	// AdminEmail is the email address of the person who will administer the team. An invitation is sent to this address.
	AdminEmail string `json:"admin_email" url:"-"`
	// Name is name of the team.
	Name string `json:"name" url:"-"`
}

// CreateTeam create a team
// Creates a team along with its default project, a staging environment, and a production environment. An admin invitation is sent to `admin_email`, onboarding is marked complete with AuthKit enabled, and the calling platform is authorized to act inside the team.
func (s *PlatformTeamService) CreateTeam(ctx context.Context, params *PlatformTeamsCreateTeamParams, opts ...RequestOption) (*Team, error) {
	var result Team
	_, err := s.client.request(ctx, "POST", "/platform/teams", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetTeam get a team
// Returns a team, and doubles as a health check on the platform's access to it. Read `production_state` before attempting to create a production environment.
func (s *PlatformTeamService) GetTeam(ctx context.Context, teamID string, opts ...RequestOption) (*Team, error) {
	var result Team
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/platform/teams/%s", url.PathEscape(teamID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
