// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// radarService handles Radar operations.
type radarService struct {
	client *Client
}

// RadarCreateAttemptParams contains the parameters for CreateAttempt.
type RadarCreateAttemptParams struct {
	// IPAddress is the IP address of the request to assess.
	IPAddress string `json:"ip_address"`
	// UserAgent is the user agent string of the request to assess.
	UserAgent string `json:"user_agent"`
	// Email is the email address of the user making the request.
	Email string `json:"email"`
	// AuthMethod is the authentication method being used.
	AuthMethod RadarStandaloneAssessRequestAuthMethod `json:"auth_method"`
	// Action is the action being performed.
	Action RadarStandaloneAssessRequestAction `json:"action"`
	// DeviceFingerprint is an optional device fingerprint for the request.
	DeviceFingerprint *string `json:"device_fingerprint,omitempty"`
	// BotScore is an optional bot detection score for the request.
	BotScore *string `json:"bot_score,omitempty"`
}

// CreateAttempt create an attempt
// Assess a request for risk using the Radar engine and receive a verdict.
func (s *radarService) CreateAttempt(ctx context.Context, params *RadarCreateAttemptParams, opts ...RequestOption) (*RadarStandaloneResponse, error) {
	var result RadarStandaloneResponse
	_, err := s.client.request(ctx, "POST", "/radar/attempts", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// RadarUpdateAttemptParams contains the parameters for UpdateAttempt.
type RadarUpdateAttemptParams struct {
	// ChallengeStatus is set to `"success"` to mark the challenge as completed.
	ChallengeStatus *string `json:"challenge_status,omitempty"`
	// AttemptStatus is set to `"success"` to mark the authentication attempt as successful.
	AttemptStatus *string `json:"attempt_status,omitempty"`
}

// UpdateAttempt update a Radar attempt
// You may optionally inform Radar that an authentication attempt or challenge was successful using this endpoint. Some Radar controls depend on tracking recent successful attempts, such as impossible travel.
func (s *radarService) UpdateAttempt(ctx context.Context, id string, params *RadarUpdateAttemptParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/radar/attempts/%s", id), nil, params, nil, opts)
	return err
}

// RadarAddListEntryParams contains the parameters for AddListEntry.
type RadarAddListEntryParams struct {
	// Entry is the value to add to the list. Must match the format of the list type (e.g. a valid IP address for `ip_address`, a valid email for `email`).
	Entry string `json:"entry"`
}

// AddListEntry add an entry to a Radar list
// Add an entry to a Radar list.
func (s *radarService) AddListEntry(ctx context.Context, typeParam RadarType, action RadarAction, params *RadarAddListEntryParams, opts ...RequestOption) (*RadarListEntryAlreadyPresentResponse, error) {
	var result RadarListEntryAlreadyPresentResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/radar/lists/%s/%s", typeParam, action), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// RadarRemoveListEntryParams contains the parameters for RemoveListEntry.
type RadarRemoveListEntryParams struct {
	// Entry is the value to remove from the list. Must match an existing entry.
	Entry string `json:"entry"`
}

// RemoveListEntry remove an entry from a Radar list
// Remove an entry from a Radar list.
func (s *radarService) RemoveListEntry(ctx context.Context, typeParam RadarType, action RadarAction, params *RadarRemoveListEntryParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/radar/lists/%s/%s", typeParam, action), nil, params, nil, opts)
	return err
}
