// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// radarService handles Radar operations.
type radarService struct {
	client *Client
}

// RadarCreateAttemptsParams contains the parameters for CreateAttempts.
type RadarCreateAttemptsParams struct {
	IPAddress string `json:"ip_address"`
	UserAgent string `json:"user_agent"`
	Email string `json:"email"`
	AuthMethod RadarStandaloneAssessRequestAuthMethod `json:"auth_method"`
	Action RadarStandaloneAssessRequestAction `json:"action"`
	DeviceFingerprint *string `json:"device_fingerprint,omitempty"`
	BotScore *string `json:"bot_score,omitempty"`
}

// CreateAttempts create an attempt
// Assess a request for risk using the Radar engine and receive a verdict.
func (s *radarService) CreateAttempts(ctx context.Context, params *RadarCreateAttemptsParams, opts ...RequestOption) (*RadarStandaloneResponse, error) {
	var result RadarStandaloneResponse
	_, err := s.client.request(ctx, "POST", "/radar/attempts", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// RadarUpdateAttemptParams contains the parameters for UpdateAttempt.
type RadarUpdateAttemptParams struct {
	ChallengeStatus *string `json:"challenge_status,omitempty"`
	AttemptStatus *string `json:"attempt_status,omitempty"`
}

// UpdateAttempt update a Radar attempt
// You may optionally inform Radar that an authentication attempt or challenge was successful using this endpoint. Some Radar controls depend on tracking recent successful attempts, such as impossible travel.
func (s *radarService) UpdateAttempt(ctx context.Context, iD string, params *RadarUpdateAttemptParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/radar/attempts/%s", iD), params, nil, opts)
	return err
}

// RadarAddListEntryParams contains the parameters for AddListEntry.
type RadarAddListEntryParams struct {
	Entry string `json:"entry"`
}

// AddListEntry add an entry to a Radar list
// Add an entry to a Radar list.
func (s *radarService) AddListEntry(ctx context.Context, typeParam RadarType, action RadarAction, params *RadarAddListEntryParams, opts ...RequestOption) (*RadarListEntryAlreadyPresentResponse, error) {
	var result RadarListEntryAlreadyPresentResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/radar/lists/%s/%s", typeParam, action), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// RadarRemoveListEntryParams contains the parameters for RemoveListEntry.
type RadarRemoveListEntryParams struct {
	Entry string `json:"entry"`
}

// RemoveListEntry remove an entry from a Radar list
// Remove an entry from a Radar list.
func (s *radarService) RemoveListEntry(ctx context.Context, typeParam RadarType, action RadarAction, params *RadarRemoveListEntryParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/radar/lists/%s/%s", typeParam, action), params, nil, opts)
	return err
}
