// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// sSOService handles SSO operations.
type sSOService struct {
	client *Client
}

// SSOListConnectionsParams contains the parameters for ListConnections.
type SSOListConnectionsParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *ConnectionsOrder `url:"order,omitempty"`
	ConnectionType *ConnectionsConnectionType `url:"connection_type,omitempty"`
	Domain *string `url:"domain,omitempty"`
	OrganizationID *string `url:"organization_id,omitempty"`
	Search *string `url:"search,omitempty"`
}

// ListConnections list Connections
// Get a list of all of your existing connections matching the criteria specified.
func (s *sSOService) ListConnections(ctx context.Context, params *SSOListConnectionsParams, opts ...RequestOption) *Iterator[Connection] {
	return newIterator[Connection](ctx, s.client, "GET", "/connections", params, "data", opts)
}

// GetConnection get a Connection
// Get the details of an existing connection.
func (s *sSOService) GetConnection(ctx context.Context, iD string, opts ...RequestOption) (*Connection, error) {
	var result Connection
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/connections/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteConnection delete a Connection
// Permanently deletes an existing connection. It cannot be undone.
func (s *sSOService) DeleteConnection(ctx context.Context, iD string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/connections/%s", iD), nil, nil, opts)
	return err
}

// SSOGetAuthorizationURLParams contains the parameters for GetAuthorizationURL.
type SSOGetAuthorizationURLParams struct {
	ProviderScopes []string `url:"provider_scopes,omitempty"`
	ProviderQueryParams map[string]string `url:"provider_query_params,omitempty"`
	ClientID string `url:"client_id"`
	Domain *string `url:"domain,omitempty"`
	Provider *SSOProvider `url:"provider,omitempty"`
	RedirectUri string `url:"redirect_uri"`
	ResponseType string `url:"response_type"`
	State *string `url:"state,omitempty"`
	Connection *string `url:"connection,omitempty"`
	Organization *string `url:"organization,omitempty"`
	DomainHint *string `url:"domain_hint,omitempty"`
	LoginHint *string `url:"login_hint,omitempty"`
	Nonce *string `url:"nonce,omitempty"`
}

// GetAuthorizationURL initiate SSO
// Initiates the single sign-on flow.
func (s *sSOService) GetAuthorizationURL(ctx context.Context, params *SSOGetAuthorizationURLParams, opts ...RequestOption) (*SSOAuthorizeURLResponse, error) {
	var result SSOAuthorizeURLResponse
	_, err := s.client.request(ctx, "GET", "/sso/authorize", nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SSOGetLogoutURLParams contains the parameters for GetLogoutURL.
type SSOGetLogoutURLParams struct {
	Token string `url:"token"`
}

// GetLogoutURL logout Redirect
// Logout allows to sign out a user from your application by triggering the identity provider sign out flow. This `GET` endpoint should be a redirection, since the identity provider user will be identified in the browser session.
// Before redirecting to this endpoint, you need to generate a short-lived logout token using the [Logout Authorize](https://workos.com/docs/reference/sso/logout/authorize) endpoint.
func (s *sSOService) GetLogoutURL(ctx context.Context, params *SSOGetLogoutURLParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "GET", "/sso/logout", params, nil, opts)
	return err
}

// SSOAuthorizeLogoutParams contains the parameters for AuthorizeLogout.
type SSOAuthorizeLogoutParams struct {
	ProfileID string `json:"profile_id"`
}

// AuthorizeLogout logout Authorize
// You should call this endpoint from your server to generate a logout token which is required for the [Logout Redirect](https://workos.com/docs/reference/sso/logout) endpoint.
func (s *sSOService) AuthorizeLogout(ctx context.Context, params *SSOAuthorizeLogoutParams, opts ...RequestOption) (*SSOLogoutAuthorizeResponse, error) {
	var result SSOLogoutAuthorizeResponse
	_, err := s.client.request(ctx, "POST", "/sso/logout/authorize", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetProfile get a User Profile
// Exchange an access token for a user's [Profile](https://workos.com/docs/reference/sso/profile). Because this profile is returned in the [Get a Profile and Token endpoint](https://workos.com/docs/reference/sso/profile/get-profile-and-token) your application usually does not need to call this endpoint. It is available for any authentication flows that require an additional endpoint to retrieve a user's profile.
func (s *sSOService) GetProfile(ctx context.Context, opts ...RequestOption) (*Profile, error) {
	var result Profile
	_, err := s.client.request(ctx, "GET", "/sso/profile", nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SSOGetProfileAndTokenParams contains the parameters for GetProfileAndToken.
type SSOGetProfileAndTokenParams struct {
	ClientID string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Code string `json:"code"`
	GrantType string `json:"grant_type"`
}

// GetProfileAndToken get a Profile and Token
// Get an access token along with the user [Profile](https://workos.com/docs/reference/sso/profile) using the code passed to your [Redirect URI](https://workos.com/docs/reference/sso/get-authorization-url/redirect-uri).
func (s *sSOService) GetProfileAndToken(ctx context.Context, params *SSOGetProfileAndTokenParams, opts ...RequestOption) (*SSOTokenResponse, error) {
	var result SSOTokenResponse
	_, err := s.client.request(ctx, "POST", "/sso/token", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
