// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// ssoService handles SSO operations.
type ssoService struct {
	client *Client
}

// SSOListConnectionsParams contains the parameters for ListConnections.
type SSOListConnectionsParams struct {
	Before         *string                    `url:"before,omitempty" json:"-"`
	After          *string                    `url:"after,omitempty" json:"-"`
	Limit          *int                       `url:"limit,omitempty" json:"-"`
	Order          *ConnectionsOrder          `url:"order,omitempty" json:"-"`
	ConnectionType *ConnectionsConnectionType `url:"connection_type,omitempty" json:"-"`
	Domain         *string                    `url:"domain,omitempty" json:"-"`
	OrganizationID *string                    `url:"organization_id,omitempty" json:"-"`
	Search         *string                    `url:"search,omitempty" json:"-"`
}

// ListConnections listConnections
// Get a list of all of your existing connections matching the criteria specified.
func (s *ssoService) ListConnections(ctx context.Context, params *SSOListConnectionsParams, opts ...RequestOption) *Iterator[Connection] {
	return newIterator[Connection](ctx, s.client, "GET", "/connections", params, "after", "data", opts)
}

// GetConnection getAConnection
// Get the details of an existing connection.
func (s *ssoService) GetConnection(ctx context.Context, id string, opts ...RequestOption) (*Connection, error) {
	var result Connection
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/connections/%s", id), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteConnection deleteAConnection
// Permanently deletes an existing connection. It cannot be undone.
func (s *ssoService) DeleteConnection(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/connections/%s", id), nil, nil, nil, opts)
	return err
}

// SSOGetAuthorizationURLParams contains the parameters for GetAuthorizationURL.
type SSOGetAuthorizationURLParams struct {
	ProviderScopes      []string          `url:"provider_scopes,omitempty" json:"-"`
	ProviderQueryParams map[string]string `url:"provider_query_params,omitempty" json:"-"`
	ClientID            string            `url:"client_id" json:"-"`
	Domain              *string           `url:"domain,omitempty" json:"-"`
	Provider            *SSOProvider      `url:"provider,omitempty" json:"-"`
	RedirectURI         string            `url:"redirect_uri" json:"-"`
	ResponseType        string            `url:"response_type" json:"-"`
	State               *string           `url:"state,omitempty" json:"-"`
	Connection          *string           `url:"connection,omitempty" json:"-"`
	Organization        *string           `url:"organization,omitempty" json:"-"`
	DomainHint          *string           `url:"domain_hint,omitempty" json:"-"`
	LoginHint           *string           `url:"login_hint,omitempty" json:"-"`
	Nonce               *string           `url:"nonce,omitempty" json:"-"`
}

// GetAuthorizationURL initiateSSO
// Initiates the single sign-on flow.
func (s *ssoService) GetAuthorizationURL(ctx context.Context, params *SSOGetAuthorizationURLParams, opts ...RequestOption) (*SSOAuthorizeURLResponse, error) {
	var result SSOAuthorizeURLResponse
	_, err := s.client.request(ctx, "GET", "/sso/authorize", params, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SSOGetLogoutURLParams contains the parameters for GetLogoutURL.
type SSOGetLogoutURLParams struct {
	Token string `url:"token" json:"-"`
}

// GetLogoutURL logoutRedirect
// Logout allows to sign out a user from your application by triggering the identity provider sign out flow. This `GET` endpoint should be a redirection, since the identity provider user will be identified in the browser session.
// Before redirecting to this endpoint, you need to generate a short-lived logout token using the [Logout Authorize](https://workos.com/docs/reference/sso/logout/authorize) endpoint.
func (s *ssoService) GetLogoutURL(ctx context.Context, params *SSOGetLogoutURLParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "GET", "/sso/logout", params, nil, nil, opts)
	return err
}

// SSOAuthorizeLogoutParams contains the parameters for AuthorizeLogout.
type SSOAuthorizeLogoutParams struct {
	ProfileID string `json:"profile_id"`
}

// AuthorizeLogout logoutAuthorize
// You should call this endpoint from your server to generate a logout token which is required for the [Logout Redirect](https://workos.com/docs/reference/sso/logout) endpoint.
func (s *ssoService) AuthorizeLogout(ctx context.Context, params *SSOAuthorizeLogoutParams, opts ...RequestOption) (*SSOLogoutAuthorizeResponse, error) {
	var result SSOLogoutAuthorizeResponse
	_, err := s.client.request(ctx, "POST", "/sso/logout/authorize", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetProfile getAUserProfile
// Exchange an access token for a user's [Profile](https://workos.com/docs/reference/sso/profile). Because this profile is returned in the [Get a Profile and Token endpoint](https://workos.com/docs/reference/sso/profile/get-profile-and-token) your application usually does not need to call this endpoint. It is available for any authentication flows that require an additional endpoint to retrieve a user's profile.
func (s *ssoService) GetProfile(ctx context.Context, opts ...RequestOption) (*Profile, error) {
	var result Profile
	_, err := s.client.request(ctx, "GET", "/sso/profile", nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SSOGetProfileAndTokenParams contains the parameters for GetProfileAndToken.
type SSOGetProfileAndTokenParams struct {
	ClientID     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Code         string `json:"code"`
	GrantType    string `json:"grant_type"`
}

// GetProfileAndToken getAProfileAndToken
// Get an access token along with the user [Profile](https://workos.com/docs/reference/sso/profile) using the code passed to your [Redirect URI](https://workos.com/docs/reference/sso/get-authorization-url/redirect-uri).
func (s *ssoService) GetProfileAndToken(ctx context.Context, params *SSOGetProfileAndTokenParams, opts ...RequestOption) (*SSOTokenResponse, error) {
	var result SSOTokenResponse
	_, err := s.client.request(ctx, "POST", "/sso/token", params, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
