// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
)

// SSOService handles SSO operations.
type SSOService struct {
	client *Client
}

// SSOCreateProtocolOptions is one of:
//   - SSOCreateProtocolOptionsSAML
//   - SSOCreateProtocolOptionsOIDC
type SSOCreateProtocolOptions interface {
	isSSOCreateProtocolOptions()
	applyToBody(map[string]any)
}

type SSOCreateProtocolOptionsSAML struct {
	SAMLOptions CreateConnectionSAMLOptions
}

func (p SSOCreateProtocolOptionsSAML) isSSOCreateProtocolOptions() {}
func (p SSOCreateProtocolOptionsSAML) applyToBody(m map[string]any) {
	m["saml_options"] = p.SAMLOptions
}

type SSOCreateProtocolOptionsOIDC struct {
	OIDCOptions CreateConnectionOIDCOptions
}

func (p SSOCreateProtocolOptionsOIDC) isSSOCreateProtocolOptions() {}
func (p SSOCreateProtocolOptionsOIDC) applyToBody(m map[string]any) {
	m["oidc_options"] = p.OIDCOptions
}

// SSOPatchProtocolOptions is one of:
//   - SSOPatchProtocolOptionsSAML
//   - SSOPatchProtocolOptionsOIDC
type SSOPatchProtocolOptions interface {
	isSSOPatchProtocolOptions()
	applyToBody(map[string]any)
}

type SSOPatchProtocolOptionsSAML struct {
	SAMLOptions PatchConnectionSAMLOptions
}

func (p SSOPatchProtocolOptionsSAML) isSSOPatchProtocolOptions() {}
func (p SSOPatchProtocolOptionsSAML) applyToBody(m map[string]any) {
	m["saml_options"] = p.SAMLOptions
}

type SSOPatchProtocolOptionsOIDC struct {
	OIDCOptions PatchConnectionOIDCOptions
}

func (p SSOPatchProtocolOptionsOIDC) isSSOPatchProtocolOptions() {}
func (p SSOPatchProtocolOptionsOIDC) applyToBody(m map[string]any) {
	m["oidc_options"] = p.OIDCOptions
}

// SSOListConnectionsParams contains the parameters for ListConnections.
type SSOListConnectionsParams struct {
	PaginationParams
	// ConnectionType is filter Connections by their type.
	ConnectionType *ConnectionsConnectionType `url:"connection_type,omitempty" json:"-"`
	// Domain is filter Connections by their associated domain.
	Domain *string `url:"domain,omitempty" json:"-"`
	// OrganizationID is filter Connections by their associated organization.
	OrganizationID *string `url:"organization_id,omitempty" json:"-"`
	// Search is searchable text to match against Connection names.
	Search *string `url:"search,omitempty" json:"-"`
}

// ListConnections
// Get a list of all of your existing connections matching the criteria specified.
func (s *SSOService) ListConnections(ctx context.Context, params *SSOListConnectionsParams, opts ...RequestOption) *Iterator[Connection] {
	return newIterator[Connection](ctx, s.client, "GET", "/connections", params, "after", "data", opts, map[string]string{"limit": "10", "order": "desc"})
}

// SSOCreateConnectionParams contains the parameters for CreateConnection.
type SSOCreateConnectionParams struct {
	// OrganizationID is unique identifier for the Organization in which the Connection resides.
	OrganizationID string `json:"organization_id" url:"-"`
	// Name is a human-readable name for the Connection. This will most commonly be the organization's name.
	Name *string `json:"name,omitempty" url:"-"`
	// ExternalID is the customer-owned identifier for the Connection.
	ExternalID *string `json:"external_id,omitempty" url:"-"`
	// ConnectionType is the type of the Connection. Only SAML and OIDC connection types may be created. When omitted, the type is inferred from the provided options.
	ConnectionType *string `json:"connection_type,omitempty" url:"-"`
	// AttributeMaps is how IdP attributes or claims map onto WorkOS profile fields. Provided fields override the defaults for the connection type.
	AttributeMaps *CreateConnectionAttributeMaps `json:"attribute_maps,omitempty" url:"-"`
	// ProtocolOptions identifies the protocol options (required).
	ProtocolOptions SSOCreateProtocolOptions `url:"-" json:"-"`
}

// MarshalJSON implements json.Marshaler for SSOCreateConnectionParams.
func (p SSOCreateConnectionParams) MarshalJSON() ([]byte, error) {
	type Alias SSOCreateConnectionParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if p.ProtocolOptions == nil {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.ProtocolOptions != nil {
		p.ProtocolOptions.applyToBody(m)
	}
	return json.Marshal(m)
}

// CreateConnection create a Connection
// Creates a new connection for an organization. Provide `saml_options` or `oidc_options` to configure the identity provider. When `external_id` matches an existing connection in the organization, that connection is returned instead of creating a duplicate.
func (s *SSOService) CreateConnection(ctx context.Context, params *SSOCreateConnectionParams, opts ...RequestOption) (*Connection, error) {
	var result Connection
	_, err := s.client.request(ctx, "POST", "/connections", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListConnectionSAMLIdpSigningCerts list IdP signing certificates
// Lists every Identity Provider signing certificate on the connection, including expired ones, oldest first.
func (s *SSOService) ListConnectionSAMLIdpSigningCerts(ctx context.Context, connectionID string, opts ...RequestOption) (*SAMLIdpSigningCertificateList, error) {
	var result SAMLIdpSigningCertificateList
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/connections/%s/saml_idp_signing_certs", url.PathEscape(connectionID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SSOCreateConnectionSAMLIdpSigningCertParams contains the parameters for CreateConnectionSAMLIdpSigningCert.
type SSOCreateConnectionSAMLIdpSigningCertParams struct {
	// Value is the PEM-encoded X.509 certificate.
	Value string `json:"value" url:"-"`
}

// CreateConnectionSAMLIdpSigningCert create an IdP signing certificate
// Adds an Identity Provider signing certificate to the connection, so SAML responses signed with its key can be verified. Use this to import a new certificate ahead of an Identity Provider rotation — the existing certificates keep working until they are deleted or expire.
func (s *SSOService) CreateConnectionSAMLIdpSigningCert(ctx context.Context, connectionID string, params *SSOCreateConnectionSAMLIdpSigningCertParams, opts ...RequestOption) (*SAMLIdpSigningCertificate, error) {
	var result SAMLIdpSigningCertificate
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/connections/%s/saml_idp_signing_certs", url.PathEscape(connectionID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteConnectionSAMLIdpSigningCert delete an IdP signing certificate
// Removes an Identity Provider signing certificate from the connection. The last remaining certificate cannot be deleted. A certificate still published in the Identity Provider metadata may be restored by a metadata refresh.
func (s *SSOService) DeleteConnectionSAMLIdpSigningCert(ctx context.Context, connectionID string, certificateID string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/connections/%s/saml_idp_signing_certs/%s", url.PathEscape(connectionID), url.PathEscape(certificateID)), nil, nil, nil, opts)
	return err
}

// ListConnectionSAMLSpEncryptionCerts list SP encryption certificates
// Lists the public certificates the Identity Provider can use to encrypt SAML responses sent to WorkOS, including expired ones, oldest first.
func (s *SSOService) ListConnectionSAMLSpEncryptionCerts(ctx context.Context, connectionID string, opts ...RequestOption) (*SAMLSpEncryptionCertificateList, error) {
	var result SAMLSpEncryptionCertificateList
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/connections/%s/saml_sp_encryption_certs", url.PathEscape(connectionID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateConnectionSAMLSpEncryptionCert create an SP encryption certificate
// Generates a new encryption key pair for the connection and returns its public certificate. WorkOS holds the private key, so the request takes no body — to bring your own key pairs, provide `saml_options.sp_encryption_key_pairs` when creating the connection instead. Creating a certificate appends rather than replaces: every active private key is tried when decrypting, which lets a rotation overlap the old and new certificates.
func (s *SSOService) CreateConnectionSAMLSpEncryptionCert(ctx context.Context, connectionID string, opts ...RequestOption) (*SAMLSpEncryptionCertificate, error) {
	var result SAMLSpEncryptionCertificate
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/connections/%s/saml_sp_encryption_certs", url.PathEscape(connectionID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteConnectionSAMLSpEncryptionCert delete an SP encryption certificate
// Removes an encryption key pair from the connection. SAML responses encrypted with its certificate can no longer be decrypted, so remove the certificate from the Identity Provider first when rotating.
func (s *SSOService) DeleteConnectionSAMLSpEncryptionCert(ctx context.Context, connectionID string, certificateID string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/connections/%s/saml_sp_encryption_certs/%s", url.PathEscape(connectionID), url.PathEscape(certificateID)), nil, nil, nil, opts)
	return err
}

// ListConnectionSAMLSpSigningCert get the SP signing certificate
// Returns the public certificate the Identity Provider can use to verify the signature of SAML requests sent by WorkOS. Responds with `404` when the connection has no request signing key pair.
func (s *SSOService) ListConnectionSAMLSpSigningCert(ctx context.Context, connectionID string, opts ...RequestOption) (*SAMLSpSigningCertificate, error) {
	var result SAMLSpSigningCertificate
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/connections/%s/saml_sp_signing_cert", url.PathEscape(connectionID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateConnectionSAMLSpSigningCert create an SP signing certificate
// Generates a new request signing key pair for the connection and returns its public certificate. WorkOS holds the private key, so the request takes no body — to bring your own key pair, provide `saml_options.sp_signing_key_pair` when creating the connection instead. A connection signs with one key pair at a time: delete the existing certificate before creating its replacement.
func (s *SSOService) CreateConnectionSAMLSpSigningCert(ctx context.Context, connectionID string, opts ...RequestOption) (*SAMLSpSigningCertificate, error) {
	var result SAMLSpSigningCertificate
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/connections/%s/saml_sp_signing_cert", url.PathEscape(connectionID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteConnectionSAMLSpSigningCert delete the SP signing certificate
// Removes the request signing key pair from the connection, after which SAML requests are sent unsigned. Delete the certificate before creating its replacement when rotating.
func (s *SSOService) DeleteConnectionSAMLSpSigningCert(ctx context.Context, connectionID string, certificateID string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/connections/%s/saml_sp_signing_cert/%s", url.PathEscape(connectionID), url.PathEscape(certificateID)), nil, nil, nil, opts)
	return err
}

// GetConnection get a Connection
// Get the details of an existing connection.
func (s *SSOService) GetConnection(ctx context.Context, id string, opts ...RequestOption) (*Connection, error) {
	var result Connection
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/connections/%s", url.PathEscape(id)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SSOUpdateConnectionParams contains the parameters for UpdateConnection.
type SSOUpdateConnectionParams struct {
	// Name is a human-readable name for the Connection.
	Name *string `json:"name,omitempty" url:"-"`
	// ExternalID is the customer-owned identifier for the Connection. Set to `null` to stop tracking one.
	ExternalID *string `json:"external_id,omitempty" url:"-"`
	// ConnectionType is the type of the Connection. Immutable after creation — it may be sent, but only with the Connection current type.
	ConnectionType *string `json:"connection_type,omitempty" url:"-"`
	// AttributeMaps is how IdP attributes or claims map onto WorkOS profile fields. Only the provided fields are updated.
	AttributeMaps *PatchConnectionAttributeMaps `json:"attribute_maps,omitempty" url:"-"`
	// ProtocolOptions optionally identifies the protocol options.
	ProtocolOptions SSOPatchProtocolOptions `url:"-" json:"-"`
	// NullFields lists JSON field names to send as an explicit null,
	// clearing the corresponding value (e.g. []string{"external_id"}).
	NullFields []string `json:"-" url:"-"`
}

// MarshalJSON implements json.Marshaler for SSOUpdateConnectionParams.
func (p SSOUpdateConnectionParams) MarshalJSON() ([]byte, error) {
	type Alias SSOUpdateConnectionParams
	data, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if p.ProtocolOptions == nil && len(p.NullFields) == 0 {
		return data, nil
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if p.ProtocolOptions != nil {
		p.ProtocolOptions.applyToBody(m)
	}
	nullable := map[string]bool{
		"external_id": true,
	}
	for _, f := range p.NullFields {
		if !nullable[f] {
			return nil, fmt.Errorf("SSOUpdateConnectionParams: %q is not a nullable field", f)
		}
		m[f] = nil
	}
	return json.Marshal(m)
}

// UpdateConnection update a Connection
// Updates an existing connection. Only the provided fields are changed; fields that accept `null` are reset to their default behavior.
func (s *SSOService) UpdateConnection(ctx context.Context, id string, params *SSOUpdateConnectionParams, opts ...RequestOption) (*Connection, error) {
	var result Connection
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/connections/%s", url.PathEscape(id)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteConnection delete a Connection
// Permanently deletes an existing connection. It cannot be undone.
func (s *SSOService) DeleteConnection(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/connections/%s", url.PathEscape(id)), nil, nil, nil, opts)
	return err
}

// SSOGetAuthorizationURLParams contains the parameters for GetAuthorizationURL.
type SSOGetAuthorizationURLParams struct {
	// ProviderScopes is additional scopes to request from the identity provider. Applicable when using OAuth or OpenID Connect connections.
	ProviderScopes []string `url:"provider_scopes,omitempty" json:"-"`
	// ProviderQueryParams is key/value pairs of query parameters to pass to the OAuth provider. Only applicable when using OAuth connections.
	ProviderQueryParams map[string]string `url:"provider_query_params,omitempty" json:"-"`
	// Domain is deprecated. Use `connection` or `organization` instead. Used to initiate SSO for a connection by domain. The domain must be associated with a connection in your WorkOS environment.
	//
	// Deprecated: this parameter is deprecated.
	Domain *string `url:"domain,omitempty" json:"-"`
	// Provider is used to initiate OAuth authentication with various providers.
	Provider *SSOProvider `url:"provider,omitempty" json:"-"`
	// RedirectURI is where to redirect the user after they complete the authentication process. You must use one of the redirect URIs configured via the [Redirects](https://dashboard.workos.com/redirects) page on the dashboard.
	RedirectURI string `url:"redirect_uri" json:"-"`
	// State is an optional parameter that can be used to encode arbitrary information to help restore application state between redirects. If included, the redirect URI received from WorkOS will contain the exact `state` that was passed.
	State *string `url:"state,omitempty" json:"-"`
	// Connection is used to initiate SSO for a connection. The value should be a WorkOS connection ID.
	// You can persist the WorkOS connection ID with application user or team identifiers. WorkOS will use the connection indicated by the connection parameter to direct the user to the corresponding IdP for authentication.
	Connection *string `url:"connection,omitempty" json:"-"`
	// Organization is used to initiate SSO for an organization. The value should be a WorkOS organization ID.
	// You can persist the WorkOS organization ID with application user or team identifiers. WorkOS will use the organization ID to determine the appropriate connection and the IdP to direct the user to for authentication.
	Organization *string `url:"organization,omitempty" json:"-"`
	// DomainHint is can be used to pre-fill the domain field when initiating authentication with Microsoft OAuth or with a Google SAML connection type.
	DomainHint *string `url:"domain_hint,omitempty" json:"-"`
	// LoginHint is can be used to pre-fill the username/email address field of the IdP sign-in page for the user, if you know their username ahead of time. Currently supported for OAuth, OpenID Connect, Okta, Entra ID, and custom SAML connections.
	LoginHint *string `url:"login_hint,omitempty" json:"-"`
	// Nonce is a random string generated by the client that is used to mitigate replay attacks.
	Nonce *string `url:"nonce,omitempty" json:"-"`
	// Prompt is if set to `login`, forces re-authentication at the identity provider. For supported SAML providers this sets `ForceAuthn="true"` in the SAML request; providers that don't support it are unaffected.
	Prompt *string `url:"prompt,omitempty" json:"-"`
}

// GetAuthorizationURL initiate SSO
// Initiates the single sign-on flow.
func (s *SSOService) GetAuthorizationURL(params *SSOGetAuthorizationURLParams, opts ...RequestOption) string {
	query := url.Values{}
	query.Set("response_type", "code")
	if s.client.clientID != "" {
		query.Set("client_id", s.client.clientID)
	}
	if params.ProviderScopes != nil {
		query.Set("provider_scopes", strings.Join(params.ProviderScopes, ","))
	}
	if params.ProviderQueryParams != nil {
		for k, v := range params.ProviderQueryParams {
			query.Set(fmt.Sprintf("provider_query_params[%s]", k), fmt.Sprintf("%v", v))
		}
	}
	if params.Domain != nil {
		query.Set("domain", *params.Domain)
	}
	if params.Provider != nil {
		query.Set("provider", fmt.Sprintf("%v", *params.Provider))
	}
	query.Set("redirect_uri", params.RedirectURI)
	if params.State != nil {
		query.Set("state", *params.State)
	}
	if params.Connection != nil {
		query.Set("connection", *params.Connection)
	}
	if params.Organization != nil {
		query.Set("organization", *params.Organization)
	}
	if params.DomainHint != nil {
		query.Set("domain_hint", *params.DomainHint)
	}
	if params.LoginHint != nil {
		query.Set("login_hint", *params.LoginHint)
	}
	if params.Nonce != nil {
		query.Set("nonce", *params.Nonce)
	}
	if params.Prompt != nil {
		query.Set("prompt", fmt.Sprintf("%v", *params.Prompt))
	}
	return s.client.buildURL("/sso/authorize", query, opts)
}

// SSOGetLogoutURLParams contains the parameters for GetLogoutURL.
type SSOGetLogoutURLParams struct {
	// Token is the logout token returned from the [Logout Authorize](https://workos.com/docs/reference/sso/logout/authorize) endpoint.
	Token string `url:"token" json:"-"`
}

// GetLogoutURL logout Redirect
// Logout allows to sign out a user from your application by triggering the identity provider sign out flow. This `GET` endpoint should be a redirection, since the identity provider user will be identified in the browser session.
// Before redirecting to this endpoint, you need to generate a short-lived logout token using the [Logout Authorize](https://workos.com/docs/reference/sso/logout/authorize) endpoint.
func (s *SSOService) GetLogoutURL(params *SSOGetLogoutURLParams, opts ...RequestOption) string {
	query := url.Values{}
	query.Set("token", params.Token)
	return s.client.buildURL("/sso/logout", query, opts)
}

// SSOAuthorizeLogoutParams contains the parameters for AuthorizeLogout.
type SSOAuthorizeLogoutParams struct {
	// ProfileID is the unique ID of the profile to log out.
	ProfileID string `json:"profile_id" url:"-"`
}

// AuthorizeLogout logout Authorize
// You should call this endpoint from your server to generate a logout token which is required for the [Logout Redirect](https://workos.com/docs/reference/sso/logout) endpoint.
func (s *SSOService) AuthorizeLogout(ctx context.Context, params *SSOAuthorizeLogoutParams, opts ...RequestOption) (*SSOLogoutAuthorizeResponse, error) {
	var result SSOLogoutAuthorizeResponse
	_, err := s.client.request(ctx, "POST", "/sso/logout/authorize", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetProfile get a User Profile
// Exchange an access token for a user's [Profile](https://workos.com/docs/reference/sso/profile). Because this profile is returned in the [Get a Profile and Token endpoint](https://workos.com/docs/reference/sso/profile/get-profile-and-token) your application usually does not need to call this endpoint. It is available for any authentication flows that require an additional endpoint to retrieve a user's profile.
func (s *SSOService) GetProfile(ctx context.Context, opts ...RequestOption) (*Profile, error) {
	var result Profile
	_, err := s.client.request(ctx, "GET", "/sso/profile", nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SSOGetProfileAndTokenParams contains the parameters for GetProfileAndToken.
type SSOGetProfileAndTokenParams struct {
	// Code is the authorization code received from the authorization callback. Required when `grant_type` is `authorization_code`.
	Code *string `json:"code,omitempty" url:"-"`
	// SubjectToken is the OIDC ID token to exchange. Required when `grant_type` is `urn:ietf:params:oauth:grant-type:token-exchange`. Must be sent in the request body.
	SubjectToken *string `json:"subject_token,omitempty" url:"-"`
	// SubjectTokenType is the type of the subject token. Required when `grant_type` is `urn:ietf:params:oauth:grant-type:token-exchange`. Must be sent in the request body.
	SubjectTokenType *string `json:"subject_token_type,omitempty" url:"-"`
	// OrganizationID is the ID of the organization whose connection the subject token is validated against. Required when `grant_type` is `urn:ietf:params:oauth:grant-type:token-exchange`. Must be sent in the request body.
	OrganizationID *string `json:"organization_id,omitempty" url:"-"`
}

// getProfileAndTokenBody is the JSON request body for GetProfileAndToken.
type getProfileAndTokenBody struct {
	GrantType        string  `json:"grant_type"`
	ClientID         string  `json:"client_id,omitempty"`
	ClientSecret     string  `json:"client_secret,omitempty"`
	Code             *string `json:"code,omitempty"`
	SubjectToken     *string `json:"subject_token,omitempty"`
	SubjectTokenType *string `json:"subject_token_type,omitempty"`
	OrganizationID   *string `json:"organization_id,omitempty"`
}

// GetProfileAndToken get a Profile and Token
// Get an access token along with the user [Profile](https://workos.com/docs/reference/sso/profile) using the code passed to your [Redirect URI](https://workos.com/docs/reference/sso/get-authorization-url/redirect-uri).
func (s *SSOService) GetProfileAndToken(ctx context.Context, params *SSOGetProfileAndTokenParams, opts ...RequestOption) (*SSOTokenResponse, error) {
	body := getProfileAndTokenBody{
		GrantType: "authorization_code",
	}
	body.ClientID = s.client.clientID
	body.ClientSecret = s.client.apiKey
	body.Code = params.Code
	body.SubjectToken = params.SubjectToken
	body.SubjectTokenType = params.SubjectTokenType
	body.OrganizationID = params.OrganizationID
	var result SSOTokenResponse
	_, err := s.client.request(ctx, "POST", "/sso/token", params, body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
