// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
	"net/url"
)

// UserManagementOrganizationMembershipGroupService handles UserManagementOrganizationMembershipGroups operations.
type UserManagementOrganizationMembershipGroupService struct {
	client *Client
}

// UserManagementOrganizationMembershipGroupsListOrganizationMembershipGroupsParams contains the parameters for ListOrganizationMembershipGroups.
type UserManagementOrganizationMembershipGroupsListOrganizationMembershipGroupsParams struct {
	PaginationParams
}

// ListOrganizationMembershipGroups list groups
// Get a list of groups that an organization membership belongs to.
func (s *UserManagementOrganizationMembershipGroupService) ListOrganizationMembershipGroups(ctx context.Context, omID string, params *UserManagementOrganizationMembershipGroupsListOrganizationMembershipGroupsParams, opts ...RequestOption) *Iterator[Group] {
	return newIterator[Group](ctx, s.client, "GET", fmt.Sprintf("/user_management/organization_memberships/%s/groups", url.PathEscape(omID)), params, "after", "data", opts, map[string]string{"limit": "10", "order": "desc"})
}
