// Code generated by oagen. DO NOT EDIT.

package workos_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/workos/workos-go/v8"
)

func TestUserManagementOrganizationMembershipGroups_ListOrganizationMembershipGroups(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		require.Equal(t, "/user_management/organization_memberships/test_omId/groups", r.URL.Path)
		require.Equal(t, "10", r.URL.Query().Get("limit"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, err := os.ReadFile("testdata/list_group.json")
		if err != nil {
			t.Fatalf("failed to read fixture: %v", err)
		}
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.UserManagementOrganizationMembershipGroups().ListOrganizationMembershipGroups(context.Background(), "test_omId", &workos.UserManagementOrganizationMembershipGroupsListOrganizationMembershipGroupsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.NotNil(t, iter)
	require.True(t, iter.Next())
	require.NoError(t, iter.Err())
	item := iter.Current()
	require.NotNil(t, item)
}

func TestUserManagementOrganizationMembershipGroups_ListOrganizationMembershipGroups_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.UserManagementOrganizationMembershipGroups().ListOrganizationMembershipGroups(context.Background(), "test_omId", &workos.UserManagementOrganizationMembershipGroupsListOrganizationMembershipGroupsParams{PaginationParams: workos.PaginationParams{Limit: ptrInt(10)}})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestUserManagementOrganizationMembershipGroups_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.UserManagementOrganizationMembershipGroups().ListOrganizationMembershipGroups(context.Background(), "test_omId", &workos.UserManagementOrganizationMembershipGroupsListOrganizationMembershipGroupsParams{})
	require.False(t, iter.Next())
	require.IsType(t, &workos.AuthenticationError{}, iter.Err())
}

func TestUserManagementOrganizationMembershipGroups_Error404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"code":"not_found","message":"Not Found"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.UserManagementOrganizationMembershipGroups().ListOrganizationMembershipGroups(context.Background(), "test_omId", &workos.UserManagementOrganizationMembershipGroupsListOrganizationMembershipGroupsParams{})
	require.False(t, iter.Next())
	require.IsType(t, &workos.NotFoundError{}, iter.Err())
}

func TestUserManagementOrganizationMembershipGroups_Error422(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(422)
		w.Write([]byte(`{"code":"unprocessable_entity","message":"Unprocessable"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.UserManagementOrganizationMembershipGroups().ListOrganizationMembershipGroups(context.Background(), "test_omId", &workos.UserManagementOrganizationMembershipGroupsListOrganizationMembershipGroupsParams{})
	require.False(t, iter.Next())
	require.IsType(t, &workos.UnprocessableEntityError{}, iter.Err())
}
