// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// userManagementService handles UserManagement operations.
type userManagementService struct {
	client *Client
}

// GetJwks get JWKS
// Returns the JSON Web Key Set (JWKS) containing the public keys used for verifying access tokens.
func (s *userManagementService) GetJwks(ctx context.Context, clientID string, opts ...RequestOption) (*JwksResponse, error) {
	var result JwksResponse
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/sso/jwks/%s", clientID), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementCreateAuthenticateParams contains the parameters for CreateAuthenticate.
type UserManagementCreateAuthenticateParams struct {
	Body interface{} `json:"-"`
}

// CreateAuthenticate authenticate
// Authenticate a user with a specified [authentication method](https://workos.com/docs/reference/authkit/authentication).
func (s *userManagementService) CreateAuthenticate(ctx context.Context, params *UserManagementCreateAuthenticateParams, opts ...RequestOption) (*AuthenticateResponse, error) {
	var result AuthenticateResponse
	_, err := s.client.request(ctx, "POST", "/user_management/authenticate", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}


// AuthenticateWithPasswordParams contains the parameters for AuthenticateWithPassword.
type AuthenticateWithPasswordParams struct {
	Email string `json:"email"`
	Password string `json:"password"`
	InvitationToken *string `json:"invitation_token,omitempty"`
}

// AuthenticateWithPassword Authenticate with password.
func (s *userManagementService) AuthenticateWithPassword(ctx context.Context, params *AuthenticateWithPasswordParams, opts ...RequestOption) (*AuthenticateResponse, error) {
	body := map[string]interface{}{
		"grant_type": "password",
		"email": params.Email,
		"password": params.Password,
	}
	if s.client.clientID != "" {
		body["client_id"] = s.client.clientID
	}
	if s.client.apiKey != "" {
		body["client_secret"] = s.client.apiKey
	}
	if params.InvitationToken != nil {
		body["invitation_token"] = *params.InvitationToken
	}
	var result AuthenticateResponse
	_, err := s.client.request(ctx, "POST", "/user_management/authenticate", body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthenticateWithCodeParams contains the parameters for AuthenticateWithCode.
type AuthenticateWithCodeParams struct {
	Code *string `json:"code,omitempty"`
}

// AuthenticateWithCode Authenticate with code.
func (s *userManagementService) AuthenticateWithCode(ctx context.Context, params *AuthenticateWithCodeParams, opts ...RequestOption) (*AuthenticateResponse, error) {
	body := map[string]interface{}{
		"grant_type": "authorization_code",
	}
	if s.client.clientID != "" {
		body["client_id"] = s.client.clientID
	}
	if s.client.apiKey != "" {
		body["client_secret"] = s.client.apiKey
	}
	if params.Code != nil {
		body["code"] = *params.Code
	}
	var result AuthenticateResponse
	_, err := s.client.request(ctx, "POST", "/user_management/authenticate", body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthenticateWithRefreshTokenParams contains the parameters for AuthenticateWithRefreshToken.
type AuthenticateWithRefreshTokenParams struct {
	RefreshToken string `json:"refresh_token"`
	OrganizationID *string `json:"organization_id,omitempty"`
}

// AuthenticateWithRefreshToken Authenticate with refresh token.
func (s *userManagementService) AuthenticateWithRefreshToken(ctx context.Context, params *AuthenticateWithRefreshTokenParams, opts ...RequestOption) (*AuthenticateResponse, error) {
	body := map[string]interface{}{
		"grant_type": "refresh_token",
		"refresh_token": params.RefreshToken,
	}
	if s.client.clientID != "" {
		body["client_id"] = s.client.clientID
	}
	if s.client.apiKey != "" {
		body["client_secret"] = s.client.apiKey
	}
	if params.OrganizationID != nil {
		body["organization_id"] = *params.OrganizationID
	}
	var result AuthenticateResponse
	_, err := s.client.request(ctx, "POST", "/user_management/authenticate", body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthenticateWithMagicAuthParams contains the parameters for AuthenticateWithMagicAuth.
type AuthenticateWithMagicAuthParams struct {
	Code *string `json:"code,omitempty"`
	Email *string `json:"email,omitempty"`
	InvitationToken *string `json:"invitation_token,omitempty"`
}

// AuthenticateWithMagicAuth Authenticate with magic auth.
func (s *userManagementService) AuthenticateWithMagicAuth(ctx context.Context, params *AuthenticateWithMagicAuthParams, opts ...RequestOption) (*AuthenticateResponse, error) {
	body := map[string]interface{}{
		"grant_type": "urn:workos:oauth:grant-type:magic-auth:code",
	}
	if s.client.clientID != "" {
		body["client_id"] = s.client.clientID
	}
	if s.client.apiKey != "" {
		body["client_secret"] = s.client.apiKey
	}
	if params.Code != nil {
		body["code"] = *params.Code
	}
	if params.Email != nil {
		body["email"] = *params.Email
	}
	if params.InvitationToken != nil {
		body["invitation_token"] = *params.InvitationToken
	}
	var result AuthenticateResponse
	_, err := s.client.request(ctx, "POST", "/user_management/authenticate", body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthenticateWithEmailVerificationParams contains the parameters for AuthenticateWithEmailVerification.
type AuthenticateWithEmailVerificationParams struct {
	Code *string `json:"code,omitempty"`
	PendingAuthenticationToken *string `json:"pending_authentication_token,omitempty"`
}

// AuthenticateWithEmailVerification Authenticate with email verification.
func (s *userManagementService) AuthenticateWithEmailVerification(ctx context.Context, params *AuthenticateWithEmailVerificationParams, opts ...RequestOption) (*AuthenticateResponse, error) {
	body := map[string]interface{}{
		"grant_type": "urn:workos:oauth:grant-type:email-verification:code",
	}
	if s.client.clientID != "" {
		body["client_id"] = s.client.clientID
	}
	if s.client.apiKey != "" {
		body["client_secret"] = s.client.apiKey
	}
	if params.Code != nil {
		body["code"] = *params.Code
	}
	if params.PendingAuthenticationToken != nil {
		body["pending_authentication_token"] = *params.PendingAuthenticationToken
	}
	var result AuthenticateResponse
	_, err := s.client.request(ctx, "POST", "/user_management/authenticate", body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthenticateWithTotpParams contains the parameters for AuthenticateWithTotp.
type AuthenticateWithTotpParams struct {
	Code *string `json:"code,omitempty"`
	PendingAuthenticationToken *string `json:"pending_authentication_token,omitempty"`
	AuthenticationChallengeID *string `json:"authentication_challenge_id,omitempty"`
}

// AuthenticateWithTotp Authenticate with totp.
func (s *userManagementService) AuthenticateWithTotp(ctx context.Context, params *AuthenticateWithTotpParams, opts ...RequestOption) (*AuthenticateResponse, error) {
	body := map[string]interface{}{
		"grant_type": "urn:workos:oauth:grant-type:mfa-totp",
	}
	if s.client.clientID != "" {
		body["client_id"] = s.client.clientID
	}
	if s.client.apiKey != "" {
		body["client_secret"] = s.client.apiKey
	}
	if params.Code != nil {
		body["code"] = *params.Code
	}
	if params.PendingAuthenticationToken != nil {
		body["pending_authentication_token"] = *params.PendingAuthenticationToken
	}
	if params.AuthenticationChallengeID != nil {
		body["authentication_challenge_id"] = *params.AuthenticationChallengeID
	}
	var result AuthenticateResponse
	_, err := s.client.request(ctx, "POST", "/user_management/authenticate", body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthenticateWithOrganizationSelectionParams contains the parameters for AuthenticateWithOrganizationSelection.
type AuthenticateWithOrganizationSelectionParams struct {
	PendingAuthenticationToken *string `json:"pending_authentication_token,omitempty"`
	OrganizationID *string `json:"organization_id,omitempty"`
}

// AuthenticateWithOrganizationSelection Authenticate with organization selection.
func (s *userManagementService) AuthenticateWithOrganizationSelection(ctx context.Context, params *AuthenticateWithOrganizationSelectionParams, opts ...RequestOption) (*AuthenticateResponse, error) {
	body := map[string]interface{}{
		"grant_type": "urn:workos:oauth:grant-type:organization-selection",
	}
	if s.client.clientID != "" {
		body["client_id"] = s.client.clientID
	}
	if s.client.apiKey != "" {
		body["client_secret"] = s.client.apiKey
	}
	if params.PendingAuthenticationToken != nil {
		body["pending_authentication_token"] = *params.PendingAuthenticationToken
	}
	if params.OrganizationID != nil {
		body["organization_id"] = *params.OrganizationID
	}
	var result AuthenticateResponse
	_, err := s.client.request(ctx, "POST", "/user_management/authenticate", body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AuthenticateWithDeviceCodeParams contains the parameters for AuthenticateWithDeviceCode.
type AuthenticateWithDeviceCodeParams struct {
	DeviceCode *string `json:"device_code,omitempty"`
}

// AuthenticateWithDeviceCode Authenticate with device code.
func (s *userManagementService) AuthenticateWithDeviceCode(ctx context.Context, params *AuthenticateWithDeviceCodeParams, opts ...RequestOption) (*AuthenticateResponse, error) {
	body := map[string]interface{}{
		"grant_type": "urn:ietf:params:oauth:grant-type:device_code",
	}
	if s.client.clientID != "" {
		body["client_id"] = s.client.clientID
	}
	if params.DeviceCode != nil {
		body["device_code"] = *params.DeviceCode
	}
	var result AuthenticateResponse
	_, err := s.client.request(ctx, "POST", "/user_management/authenticate", body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
// UserManagementGetAuthorizationURLParams contains the parameters for GetAuthorizationURL.
type UserManagementGetAuthorizationURLParams struct {
	CodeChallengeMethod *string `url:"code_challenge_method,omitempty"`
	CodeChallenge *string `url:"code_challenge,omitempty"`
	DomainHint *string `url:"domain_hint,omitempty"`
	ConnectionID *string `url:"connection_id,omitempty"`
	ProviderQueryParams map[string]string `url:"provider_query_params,omitempty"`
	ProviderScopes []string `url:"provider_scopes,omitempty"`
	InvitationToken *string `url:"invitation_token,omitempty"`
	ScreenHint *UserManagementAuthenticationScreenHint `url:"screen_hint,omitempty"`
	LoginHint *string `url:"login_hint,omitempty"`
	Provider *UserManagementAuthenticationProvider `url:"provider,omitempty"`
	Prompt *string `url:"prompt,omitempty"`
	State *string `url:"state,omitempty"`
	OrganizationID *string `url:"organization_id,omitempty"`
	ResponseType string `url:"response_type"`
	RedirectUri string `url:"redirect_uri"`
	ClientID string `url:"client_id"`
}

// GetAuthorizationURL get an authorization URL
// Generates an OAuth 2.0 authorization URL to authenticate a user with AuthKit or SSO.
func (s *userManagementService) GetAuthorizationURL(ctx context.Context, params *UserManagementGetAuthorizationURLParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "GET", "/user_management/authorize", params, nil, opts)
	return err
}

// UserManagementCreateDeviceParams contains the parameters for CreateDevice.
type UserManagementCreateDeviceParams struct {
	ClientID string `json:"client_id"`
}

// CreateDevice get device authorization URL
// Initiates the CLI Auth flow by requesting a device code and verification URLs. This endpoint implements the OAuth 2.0 Device Authorization Flow ([RFC 8628](https://datatracker.ietf.org/doc/html/rfc8628)) and is designed for command-line applications or other devices with limited input capabilities.
func (s *userManagementService) CreateDevice(ctx context.Context, params *UserManagementCreateDeviceParams, opts ...RequestOption) (*DeviceAuthorizationResponse, error) {
	var result DeviceAuthorizationResponse
	_, err := s.client.request(ctx, "POST", "/user_management/authorize/device", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementGetLogoutURLParams contains the parameters for GetLogoutURL.
type UserManagementGetLogoutURLParams struct {
	SessionID string `url:"session_id"`
	ReturnTo *string `url:"return_to,omitempty"`
}

// GetLogoutURL logout
// Logout a user from the current [session](https://workos.com/docs/reference/authkit/session).
func (s *userManagementService) GetLogoutURL(ctx context.Context, params *UserManagementGetLogoutURLParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "GET", "/user_management/sessions/logout", params, nil, opts)
	return err
}

// UserManagementRevokeSessionParams contains the parameters for RevokeSession.
type UserManagementRevokeSessionParams struct {
	SessionID string `json:"session_id"`
	ReturnTo *string `json:"return_to,omitempty"`
}

// RevokeSession revoke Session
// Revoke a [user session](https://workos.com/docs/reference/authkit/session).
func (s *userManagementService) RevokeSession(ctx context.Context, params *UserManagementRevokeSessionParams, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "POST", "/user_management/sessions/revoke", params, nil, opts)
	return err
}

// UserManagementCreateCORSOriginsParams contains the parameters for CreateCORSOrigins.
type UserManagementCreateCORSOriginsParams struct {
	Origin string `json:"origin"`
}

// CreateCORSOrigins create a CORS origin
// Creates a new CORS origin for the current environment. CORS origins allow browser-based applications to make requests to the WorkOS API.
func (s *userManagementService) CreateCORSOrigins(ctx context.Context, params *UserManagementCreateCORSOriginsParams, opts ...RequestOption) (*CORSOriginResponse, error) {
	var result CORSOriginResponse
	_, err := s.client.request(ctx, "POST", "/user_management/cors_origins", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetEmailVerification get an email verification code
// Get the details of an existing email verification code that can be used to send an email to a user for verification.
func (s *userManagementService) GetEmailVerification(ctx context.Context, iD string, opts ...RequestOption) (*EmailVerification, error) {
	var result EmailVerification
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/email_verification/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementCreatePasswordResetParams contains the parameters for CreatePasswordReset.
type UserManagementCreatePasswordResetParams struct {
	Email string `json:"email"`
}

// CreatePasswordReset create a password reset token
// Creates a one-time token that can be used to reset a user's password.
func (s *userManagementService) CreatePasswordReset(ctx context.Context, params *UserManagementCreatePasswordResetParams, opts ...RequestOption) (*PasswordReset, error) {
	var result PasswordReset
	_, err := s.client.request(ctx, "POST", "/user_management/password_reset", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementConfirmPasswordResetParams contains the parameters for ConfirmPasswordReset.
type UserManagementConfirmPasswordResetParams struct {
	Token string `json:"token"`
	NewPassword string `json:"new_password"`
}

// ConfirmPasswordReset reset the password
// Sets a new password using the `token` query parameter from the link that the user received. Successfully resetting the password will verify a user's email, if it hasn't been verified yet.
func (s *userManagementService) ConfirmPasswordReset(ctx context.Context, params *UserManagementConfirmPasswordResetParams, opts ...RequestOption) (*ResetPasswordResponse, error) {
	var result ResetPasswordResponse
	_, err := s.client.request(ctx, "POST", "/user_management/password_reset/confirm", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetPasswordReset get a password reset token
// Get the details of an existing password reset token that can be used to reset a user's password.
func (s *userManagementService) GetPasswordReset(ctx context.Context, iD string, opts ...RequestOption) (*PasswordReset, error) {
	var result PasswordReset
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/password_reset/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementListUsersParams contains the parameters for ListUsers.
type UserManagementListUsersParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *UserManagementUsersOrder `url:"order,omitempty"`
	Organization *string `url:"organization,omitempty"`
	OrganizationID *string `url:"organization_id,omitempty"`
	Email *string `url:"email,omitempty"`
}

// ListUsers list users
// Get a list of all of your existing users matching the criteria specified.
func (s *userManagementService) ListUsers(ctx context.Context, params *UserManagementListUsersParams, opts ...RequestOption) *Iterator[User] {
	return newIterator[User](ctx, s.client, "GET", "/user_management/users", params, "data", opts)
}

// UserManagementCreateUsersParams contains the parameters for CreateUsers.
type UserManagementCreateUsersParams struct {
	Email string `json:"email"`
	Password *string `json:"password,omitempty"`
	PasswordHash *string `json:"password_hash,omitempty"`
	PasswordHashType *CreateUserPasswordHashType `json:"password_hash_type,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	EmailVerified *bool `json:"email_verified,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	ExternalID *string `json:"external_id,omitempty"`
}

// CreateUsers create a user
// Create a new user in the current environment.
func (s *userManagementService) CreateUsers(ctx context.Context, params *UserManagementCreateUsersParams, opts ...RequestOption) (*User, error) {
	var result User
	_, err := s.client.request(ctx, "POST", "/user_management/users", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetUserByExternalID get a user by external ID
// Get the details of an existing user by an [external identifier](https://workos.com/docs/authkit/metadata/external-identifiers).
func (s *userManagementService) GetUserByExternalID(ctx context.Context, externalID string, opts ...RequestOption) (*User, error) {
	var result User
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/users/external_id/%s", externalID), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetUser get a user
// Get the details of an existing user.
func (s *userManagementService) GetUser(ctx context.Context, iD string, opts ...RequestOption) (*User, error) {
	var result User
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/users/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementUpdateUserParams contains the parameters for UpdateUser.
type UserManagementUpdateUserParams struct {
	Email *string `json:"email,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	EmailVerified *bool `json:"email_verified,omitempty"`
	Password *string `json:"password,omitempty"`
	PasswordHash *string `json:"password_hash,omitempty"`
	PasswordHashType *UpdateUserPasswordHashType `json:"password_hash_type,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	ExternalID *string `json:"external_id,omitempty"`
	Locale *string `json:"locale,omitempty"`
}

// UpdateUser update a user
// Updates properties of a user. The omitted properties will be left unchanged.
func (s *userManagementService) UpdateUser(ctx context.Context, iD string, params *UserManagementUpdateUserParams, opts ...RequestOption) (*User, error) {
	var result User
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/user_management/users/%s", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteUser delete a user
// Permanently deletes a user in the current environment. It cannot be undone.
func (s *userManagementService) DeleteUser(ctx context.Context, iD string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/user_management/users/%s", iD), nil, nil, opts)
	return err
}

// UserManagementConfirmEmailChangeParams contains the parameters for ConfirmEmailChange.
type UserManagementConfirmEmailChangeParams struct {
	Code string `json:"code"`
}

// ConfirmEmailChange confirm email change
// Confirms an email change using the one-time code received by the user.
func (s *userManagementService) ConfirmEmailChange(ctx context.Context, iD string, params *UserManagementConfirmEmailChangeParams, opts ...RequestOption) (*EmailChangeConfirmation, error) {
	var result EmailChangeConfirmation
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/user_management/users/%s/email_change/confirm", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementSendEmailChangeParams contains the parameters for SendEmailChange.
type UserManagementSendEmailChangeParams struct {
	NewEmail string `json:"new_email"`
}

// SendEmailChange send email change code
// Sends an email that contains a one-time code used to change a user's email address.
func (s *userManagementService) SendEmailChange(ctx context.Context, iD string, params *UserManagementSendEmailChangeParams, opts ...RequestOption) (*EmailChange, error) {
	var result EmailChange
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/user_management/users/%s/email_change/send", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementConfirmEmailVerificationParams contains the parameters for ConfirmEmailVerification.
type UserManagementConfirmEmailVerificationParams struct {
	Code string `json:"code"`
}

// ConfirmEmailVerification verify email
// Verifies an email address using the one-time code received by the user.
func (s *userManagementService) ConfirmEmailVerification(ctx context.Context, iD string, params *UserManagementConfirmEmailVerificationParams, opts ...RequestOption) (*VerifyEmailResponse, error) {
	var result VerifyEmailResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/user_management/users/%s/email_verification/confirm", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SendEmailVerification send verification email
// Sends an email that contains a one-time code used to verify a user’s email address.
func (s *userManagementService) SendEmailVerification(ctx context.Context, iD string, opts ...RequestOption) (*SendVerificationEmailResponse, error) {
	var result SendVerificationEmailResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/user_management/users/%s/email_verification/send", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListUserIdentities get user identities
// Get a list of identities associated with the user. A user can have multiple associated identities after going through [identity linking](https://workos.com/docs/authkit/identity-linking). Currently only OAuth identities are supported. More provider types may be added in the future.
func (s *userManagementService) ListUserIdentities(ctx context.Context, iD string, opts ...RequestOption) (*UserIdentitiesGetItem, error) {
	var result UserIdentitiesGetItem
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/users/%s/identities", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementListUserSessionsParams contains the parameters for ListUserSessions.
type UserManagementListUserSessionsParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *UserManagementUsersOrder `url:"order,omitempty"`
}

// ListUserSessions list sessions
// Get a list of all active sessions for a specific user.
func (s *userManagementService) ListUserSessions(ctx context.Context, iD string, params *UserManagementListUserSessionsParams, opts ...RequestOption) *Iterator[UserSessionsListItem] {
	return newIterator[UserSessionsListItem](ctx, s.client, "GET", fmt.Sprintf("/user_management/users/%s/sessions", iD), params, "data", opts)
}

// UserManagementListInvitationsParams contains the parameters for ListInvitations.
type UserManagementListInvitationsParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *UserManagementInvitationsOrder `url:"order,omitempty"`
	OrganizationID *string `url:"organization_id,omitempty"`
	Email *string `url:"email,omitempty"`
}

// ListInvitations list invitations
// Get a list of all of invitations matching the criteria specified.
func (s *userManagementService) ListInvitations(ctx context.Context, params *UserManagementListInvitationsParams, opts ...RequestOption) *Iterator[UserInvite] {
	return newIterator[UserInvite](ctx, s.client, "GET", "/user_management/invitations", params, "data", opts)
}

// UserManagementCreateInvitationsParams contains the parameters for CreateInvitations.
type UserManagementCreateInvitationsParams struct {
	Email string `json:"email"`
	OrganizationID *string `json:"organization_id,omitempty"`
	RoleSlug *string `json:"role_slug,omitempty"`
	ExpiresInDays *int `json:"expires_in_days,omitempty"`
	InviterUserID *string `json:"inviter_user_id,omitempty"`
	Locale *CreateUserInviteOptionsLocale `json:"locale,omitempty"`
}

// CreateInvitations send an invitation
// Sends an invitation email to the recipient.
func (s *userManagementService) CreateInvitations(ctx context.Context, params *UserManagementCreateInvitationsParams, opts ...RequestOption) (*UserInvite, error) {
	var result UserInvite
	_, err := s.client.request(ctx, "POST", "/user_management/invitations", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetByToken find an invitation by token
// Retrieve an existing invitation using the token.
func (s *userManagementService) GetByToken(ctx context.Context, token string, opts ...RequestOption) (*UserInvite, error) {
	var result UserInvite
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/invitations/by_token/%s", token), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetInvitation get an invitation
// Get the details of an existing invitation.
func (s *userManagementService) GetInvitation(ctx context.Context, iD string, opts ...RequestOption) (*UserInvite, error) {
	var result UserInvite
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/invitations/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AcceptInvitation accept an invitation
// Accepts an invitation and, if linked to an organization, activates the user's membership in that organization.
func (s *userManagementService) AcceptInvitation(ctx context.Context, iD string, opts ...RequestOption) (*Invitation, error) {
	var result Invitation
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/user_management/invitations/%s/accept", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementResendInvitationParams contains the parameters for ResendInvitation.
type UserManagementResendInvitationParams struct {
	Locale *ResendUserInviteOptionsLocale `json:"locale,omitempty"`
}

// ResendInvitation resend an invitation
// Resends an invitation email to the recipient. The invitation must be in a pending state.
func (s *userManagementService) ResendInvitation(ctx context.Context, iD string, params *UserManagementResendInvitationParams, opts ...RequestOption) (*UserInvite, error) {
	var result UserInvite
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/user_management/invitations/%s/resend", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// RevokeInvitation revoke an invitation
// Revokes an existing invitation.
func (s *userManagementService) RevokeInvitation(ctx context.Context, iD string, opts ...RequestOption) (*Invitation, error) {
	var result Invitation
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/user_management/invitations/%s/revoke", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementUpdateJWTTemplateParams contains the parameters for UpdateJWTTemplate.
type UserManagementUpdateJWTTemplateParams struct {
	Content string `json:"content"`
}

// UpdateJWTTemplate update JWT template
// Update the JWT template for the current environment.
func (s *userManagementService) UpdateJWTTemplate(ctx context.Context, params *UserManagementUpdateJWTTemplateParams, opts ...RequestOption) (*JWTTemplateResponse, error) {
	var result JWTTemplateResponse
	_, err := s.client.request(ctx, "PUT", "/user_management/jwt_template", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementCreateMagicAuthParams contains the parameters for CreateMagicAuth.
type UserManagementCreateMagicAuthParams struct {
	Email string `json:"email"`
	InvitationToken *string `json:"invitation_token,omitempty"`
}

// CreateMagicAuth create a Magic Auth code
// Creates a one-time authentication code that can be sent to the user's email address. The code expires in 10 minutes. To verify the code, [authenticate the user with Magic Auth](https://workos.com/docs/reference/authkit/authentication/magic-auth).
func (s *userManagementService) CreateMagicAuth(ctx context.Context, params *UserManagementCreateMagicAuthParams, opts ...RequestOption) (*MagicAuth, error) {
	var result MagicAuth
	_, err := s.client.request(ctx, "POST", "/user_management/magic_auth", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetMagicAuth get Magic Auth code details
// Get the details of an existing [Magic Auth](https://workos.com/docs/reference/authkit/magic-auth) code that can be used to send an email to a user for authentication.
func (s *userManagementService) GetMagicAuth(ctx context.Context, iD string, opts ...RequestOption) (*MagicAuth, error) {
	var result MagicAuth
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/magic_auth/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementListOrganizationMembershipsParams contains the parameters for ListOrganizationMemberships.
type UserManagementListOrganizationMembershipsParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *UserManagementOrganizationMembershipOrder `url:"order,omitempty"`
	OrganizationID *string `url:"organization_id,omitempty"`
	Statuses []UserManagementOrganizationMembershipStatuses `url:"statuses,omitempty"`
	UserID *string `url:"user_id,omitempty"`
}

// ListOrganizationMemberships list organization memberships
// Get a list of all organization memberships matching the criteria specified. At least one of `user_id` or `organization_id` must be provided. By default only active memberships are returned. Use the `statuses` parameter to filter by other statuses.
func (s *userManagementService) ListOrganizationMemberships(ctx context.Context, params *UserManagementListOrganizationMembershipsParams, opts ...RequestOption) *Iterator[UserOrganizationMembership] {
	return newIterator[UserOrganizationMembership](ctx, s.client, "GET", "/user_management/organization_memberships", params, "data", opts)
}

// UserManagementCreateOrganizationMembershipsParams contains the parameters for CreateOrganizationMemberships.
type UserManagementCreateOrganizationMembershipsParams struct {
	UserID string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
	RoleSlug *string `json:"role_slug,omitempty"`
	RoleSlugs []string `json:"role_slugs,omitempty"`
}

// CreateOrganizationMemberships create an organization membership
// Creates a new `active` organization membership for the given organization and user.
// Calling this API with an organization and user that match an `inactive` organization membership will activate the membership with the specified role(s).
func (s *userManagementService) CreateOrganizationMemberships(ctx context.Context, params *UserManagementCreateOrganizationMembershipsParams, opts ...RequestOption) (*OrganizationMembership, error) {
	var result OrganizationMembership
	_, err := s.client.request(ctx, "POST", "/user_management/organization_memberships", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOrganizationMembership get an organization membership
// Get the details of an existing organization membership.
func (s *userManagementService) GetOrganizationMembership(ctx context.Context, iD string, opts ...RequestOption) (*UserOrganizationMembership, error) {
	var result UserOrganizationMembership
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/user_management/organization_memberships/%s", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementUpdateOrganizationMembershipParams contains the parameters for UpdateOrganizationMembership.
type UserManagementUpdateOrganizationMembershipParams struct {
	RoleSlug *string `json:"role_slug,omitempty"`
	RoleSlugs []string `json:"role_slugs,omitempty"`
}

// UpdateOrganizationMembership update an organization membership
// Update the details of an existing organization membership.
func (s *userManagementService) UpdateOrganizationMembership(ctx context.Context, iD string, params *UserManagementUpdateOrganizationMembershipParams, opts ...RequestOption) (*UserOrganizationMembership, error) {
	var result UserOrganizationMembership
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/user_management/organization_memberships/%s", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteOrganizationMembership delete an organization membership
// Permanently deletes an existing organization membership. It cannot be undone.
func (s *userManagementService) DeleteOrganizationMembership(ctx context.Context, iD string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/user_management/organization_memberships/%s", iD), nil, nil, opts)
	return err
}

// DeactivateOrganizationMembership deactivate an organization membership
// Deactivates an `active` organization membership. Emits an [organization_membership.updated](https://workos.com/docs/events/organization-membership) event upon successful deactivation.
// - Deactivating an `inactive` membership is a no-op and does not emit an event.
// - Deactivating a `pending` membership returns an error. This membership should be [deleted](https://workos.com/docs/reference/authkit/organization-membership/delete) instead.
// See the [membership management documentation](https://workos.com/docs/authkit/users-organizations/organizations/membership-management) for additional details.
func (s *userManagementService) DeactivateOrganizationMembership(ctx context.Context, iD string, opts ...RequestOption) (*OrganizationMembership, error) {
	var result OrganizationMembership
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/user_management/organization_memberships/%s/deactivate", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ReactivateOrganizationMembership reactivate an organization membership
// Reactivates an `inactive` organization membership, retaining the pre-existing role(s). Emits an [organization_membership.updated](https://workos.com/docs/events/organization-membership) event upon successful reactivation.
// - Reactivating an `active` membership is a no-op and does not emit an event.
// - Reactivating a `pending` membership returns an error. The user needs to [accept the invitation](https://workos.com/docs/authkit/invitations) instead.
// See the [membership management documentation](https://workos.com/docs/authkit/users-organizations/organizations/membership-management) for additional details.
func (s *userManagementService) ReactivateOrganizationMembership(ctx context.Context, iD string, opts ...RequestOption) (*UserOrganizationMembership, error) {
	var result UserOrganizationMembership
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/user_management/organization_memberships/%s/reactivate", iD), nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementCreateRedirectUrisParams contains the parameters for CreateRedirectUris.
type UserManagementCreateRedirectUrisParams struct {
	Uri string `json:"uri"`
}

// CreateRedirectUris create a redirect URI
// Creates a new redirect URI for an environment.
func (s *userManagementService) CreateRedirectUris(ctx context.Context, params *UserManagementCreateRedirectUrisParams, opts ...RequestOption) (*RedirectUri, error) {
	var result RedirectUri
	_, err := s.client.request(ctx, "POST", "/user_management/redirect_uris", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UserManagementListUserAuthorizedApplicationsParams contains the parameters for ListUserAuthorizedApplications.
type UserManagementListUserAuthorizedApplicationsParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *UserManagementUsersAuthorizedApplicationsOrder `url:"order,omitempty"`
}

// ListUserAuthorizedApplications list authorized applications
// Get a list of all Connect applications that the user has authorized.
func (s *userManagementService) ListUserAuthorizedApplications(ctx context.Context, userID string, params *UserManagementListUserAuthorizedApplicationsParams, opts ...RequestOption) *Iterator[AuthorizedConnectApplicationListData] {
	return newIterator[AuthorizedConnectApplicationListData](ctx, s.client, "GET", fmt.Sprintf("/user_management/users/%s/authorized_applications", userID), params, "data", opts)
}

// DeleteUserAuthorizedApplication delete an authorized application
// Delete an existing Authorized Connect Application.
func (s *userManagementService) DeleteUserAuthorizedApplication(ctx context.Context, applicationID string, userID string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/user_management/users/%s/authorized_applications/%s", applicationID, userID), nil, nil, opts)
	return err
}
