// Code generated by oagen. DO NOT EDIT.

package workos_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/workos/workos-go/v6"
)

func TestWebhooks_ListEndpoints(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "GET", r.Method)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, _ := os.ReadFile("testdata/list_webhook_endpoint_list.json")
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Webhooks().ListEndpoints(context.Background(), &workos.WebhooksListEndpointsParams{})
	require.NotNil(t, iter)
}

func TestWebhooks_ListEndpoints_Empty(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[],"list_metadata":{"before":null,"after":null}}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Webhooks().ListEndpoints(context.Background(), &workos.WebhooksListEndpointsParams{})
	require.False(t, iter.Next())
	require.NoError(t, iter.Err())
}

func TestWebhooks_CreateEndpoints(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "POST", r.Method)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, _ := os.ReadFile("testdata/webhook_endpoint_json.json")
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Webhooks().CreateEndpoints(context.Background(), &workos.WebhooksCreateEndpointsParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestWebhooks_UpdateEndpoint(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "PATCH", r.Method)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		fixture, _ := os.ReadFile("testdata/webhook_endpoint_json.json")
		w.Write(fixture)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	result, err := client.Webhooks().UpdateEndpoint(context.Background(), "test_id", &workos.WebhooksUpdateEndpointParams{})
	require.NoError(t, err)
	require.NotNil(t, result)
}

func TestWebhooks_DeleteEndpoint(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "DELETE", r.Method)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	err := client.Webhooks().DeleteEndpoint(context.Background(), "test_id")
	require.NoError(t, err)
}

func TestWebhooks_Error401(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"code":"unauthorized","message":"Unauthorized"}`))
	}))
	defer server.Close()

	client := workos.NewClient("sk_test", workos.WithBaseURL(server.URL))
	iter := client.Webhooks().ListEndpoints(context.Background(), &workos.WebhooksListEndpointsParams{})
	require.False(t, iter.Next())
	require.IsType(t, &workos.AuthenticationError{}, iter.Err())
}
