// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// webhooksService handles Webhooks operations.
type webhooksService struct {
	client *Client
}

// WebhooksListWebhookEndpointsParams contains the parameters for ListWebhookEndpoints.
type WebhooksListWebhookEndpointsParams struct {
	Before *string `url:"before,omitempty"`
	After *string `url:"after,omitempty"`
	Limit *float64 `url:"limit,omitempty"`
	Order *WebhooksOrder `url:"order,omitempty"`
}

// ListWebhookEndpoints list Webhook Endpoints
// Get a list of all of your existing webhook endpoints.
func (s *webhooksService) ListWebhookEndpoints(ctx context.Context, params *WebhooksListWebhookEndpointsParams, opts ...RequestOption) *Iterator[WebhookEndpointJSON] {
	return newIterator[WebhookEndpointJSON](ctx, s.client, "GET", "/webhook_endpoints", params, "data", opts)
}

// WebhooksCreateWebhookEndpointsParams contains the parameters for CreateWebhookEndpoints.
type WebhooksCreateWebhookEndpointsParams struct {
	EndpointURL string `json:"endpoint_url"`
	Events []CreateWebhookEndpointEvents `json:"events"`
}

// CreateWebhookEndpoints create a Webhook Endpoint
// Create a new webhook endpoint to receive event notifications.
func (s *webhooksService) CreateWebhookEndpoints(ctx context.Context, params *WebhooksCreateWebhookEndpointsParams, opts ...RequestOption) (*WebhookEndpointJSON, error) {
	var result WebhookEndpointJSON
	_, err := s.client.request(ctx, "POST", "/webhook_endpoints", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// WebhooksUpdateWebhookEndpointParams contains the parameters for UpdateWebhookEndpoint.
type WebhooksUpdateWebhookEndpointParams struct {
	EndpointURL *string `json:"endpoint_url,omitempty"`
	Status *UpdateWebhookEndpointStatus `json:"status,omitempty"`
	Events []UpdateWebhookEndpointEvents `json:"events,omitempty"`
}

// UpdateWebhookEndpoint update a Webhook Endpoint
// Update the properties of an existing webhook endpoint.
func (s *webhooksService) UpdateWebhookEndpoint(ctx context.Context, iD string, params *WebhooksUpdateWebhookEndpointParams, opts ...RequestOption) (*WebhookEndpointJSON, error) {
	var result WebhookEndpointJSON
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/webhook_endpoints/%s", iD), params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteWebhookEndpoint delete a Webhook Endpoint
// Delete an existing webhook endpoint.
func (s *webhooksService) DeleteWebhookEndpoint(ctx context.Context, iD string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/webhook_endpoints/%s", iD), nil, nil, opts)
	return err
}
