// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
	"fmt"
)

// webhookService handles Webhooks operations.
type webhookService struct {
	client *Client
}

// WebhooksListEndpointsParams contains the parameters for ListEndpoints.
type WebhooksListEndpointsParams struct {
	Before *string        `url:"before,omitempty" json:"-"`
	After  *string        `url:"after,omitempty" json:"-"`
	Limit  *int           `url:"limit,omitempty" json:"-"`
	Order  *WebhooksOrder `url:"order,omitempty" json:"-"`
}

// ListEndpoints listWebhookEndpoints
// Get a list of all of your existing webhook endpoints.
func (s *webhookService) ListEndpoints(ctx context.Context, params *WebhooksListEndpointsParams, opts ...RequestOption) *Iterator[WebhookEndpointJSON] {
	return newIterator[WebhookEndpointJSON](ctx, s.client, "GET", "/webhook_endpoints", params, "after", "data", opts)
}

// WebhooksCreateEndpointsParams contains the parameters for CreateEndpoints.
type WebhooksCreateEndpointsParams struct {
	EndpointURL string                        `json:"endpoint_url"`
	Events      []CreateWebhookEndpointEvents `json:"events"`
}

// CreateEndpoints createAWebhookEndpoint
// Create a new webhook endpoint to receive event notifications.
func (s *webhookService) CreateEndpoints(ctx context.Context, params *WebhooksCreateEndpointsParams, opts ...RequestOption) (*WebhookEndpointJSON, error) {
	var result WebhookEndpointJSON
	_, err := s.client.request(ctx, "POST", "/webhook_endpoints", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// WebhooksUpdateEndpointParams contains the parameters for UpdateEndpoint.
type WebhooksUpdateEndpointParams struct {
	EndpointURL *string                       `json:"endpoint_url,omitempty"`
	Status      *UpdateWebhookEndpointStatus  `json:"status,omitempty"`
	Events      []UpdateWebhookEndpointEvents `json:"events,omitempty"`
}

// UpdateEndpoint updateAWebhookEndpoint
// Update the properties of an existing webhook endpoint.
func (s *webhookService) UpdateEndpoint(ctx context.Context, id string, params *WebhooksUpdateEndpointParams, opts ...RequestOption) (*WebhookEndpointJSON, error) {
	var result WebhookEndpointJSON
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/webhook_endpoints/%s", id), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteEndpoint deleteAWebhookEndpoint
// Delete an existing webhook endpoint.
func (s *webhookService) DeleteEndpoint(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/webhook_endpoints/%s", id), nil, nil, nil, opts)
	return err
}
