// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
)

// widgetService handles Widgets operations.
type widgetService struct {
	client *Client
}

// WidgetsCreateTokenParams contains the parameters for CreateToken.
type WidgetsCreateTokenParams struct {
	// OrganizationID is the ID of the organization to scope the widget session to.
	OrganizationID string `json:"organization_id"`
	// UserID is the ID of the user to issue the widget session token for.
	UserID *string `json:"user_id,omitempty"`
	// Scopes is the scopes to grant the widget session.
	Scopes []WidgetSessionTokenScopes `json:"scopes,omitempty"`
}

// CreateToken generate a widget token
// Generate a widget token scoped to an organization and user with the specified scopes.
func (s *widgetService) CreateToken(ctx context.Context, params *WidgetsCreateTokenParams, opts ...RequestOption) (*WidgetSessionTokenResponse, error) {
	var result WidgetSessionTokenResponse
	_, err := s.client.request(ctx, "POST", "/widgets/token", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
