// Code generated by oagen. DO NOT EDIT.

package workos

import (
	"context"
)

// widgetsService handles Widgets operations.
type widgetsService struct {
	client *Client
}

// WidgetsCreateTokenParams contains the parameters for CreateToken.
type WidgetsCreateTokenParams struct {
	OrganizationID string `json:"organization_id"`
	UserID *string `json:"user_id,omitempty"`
	Scopes []WidgetSessionTokenScopes `json:"scopes,omitempty"`
}

// CreateToken generate a widget token
// Generate a widget token scoped to an organization and user with the specified scopes.
func (s *widgetsService) CreateToken(ctx context.Context, params *WidgetsCreateTokenParams, opts ...RequestOption) (*WidgetSessionTokenResponse, error) {
	var result WidgetSessionTokenResponse
	_, err := s.client.request(ctx, "POST", "/widgets/token", params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
