// Code generated by oagen. DO NOT EDIT.

package workos

import "net/http"

// Client is the WorkOS API client.
type Client struct {
	apiKey     string
	clientID   string
	baseURL    string
	httpClient *http.Client
	maxRetries int

	apiKeys             *APIKeyService
	multiFactorAuth     *MultiFactorAuthService
	connect             *ConnectService
	authorization       *AuthorizationService
	sso                 *SSOService
	pipes               *PipeService
	directorySync       *DirectorySyncService
	events              *EventService
	featureFlags        *FeatureFlagService
	organizationDomains *OrganizationDomainService
	organizations       *OrganizationService
	adminPortal         *AdminPortalService
	radar               *RadarService
	userManagement      *UserManagementService
	webhooks            *WebhookService
	widgets             *WidgetService
	auditLogs           *AuditLogService
}

// NewClient creates a new WorkOS API client.
func NewClient(apiKey string, opts ...ClientOption) *Client {
	c := &Client{
		apiKey:     apiKey,
		baseURL:    defaultBaseURL,
		httpClient: &http.Client{Timeout: defaultTimeout},
		maxRetries: defaultMaxRetries,
	}
	for _, opt := range opts {
		opt(c)
	}
	c.apiKeys = &APIKeyService{client: c}
	c.multiFactorAuth = &MultiFactorAuthService{client: c}
	c.connect = &ConnectService{client: c}
	c.authorization = &AuthorizationService{client: c}
	c.sso = &SSOService{client: c}
	c.pipes = &PipeService{client: c}
	c.directorySync = &DirectorySyncService{client: c}
	c.events = &EventService{client: c}
	c.featureFlags = &FeatureFlagService{client: c}
	c.organizationDomains = &OrganizationDomainService{client: c}
	c.organizations = &OrganizationService{client: c}
	c.adminPortal = &AdminPortalService{client: c}
	c.radar = &RadarService{client: c}
	c.userManagement = &UserManagementService{client: c}
	c.webhooks = &WebhookService{client: c}
	c.widgets = &WidgetService{client: c}
	c.auditLogs = &AuditLogService{client: c}
	return c
}

// APIKeys returns the APIKeys service.
func (c *Client) APIKeys() *APIKeyService {
	return c.apiKeys
}

// MultiFactorAuth returns the MultiFactorAuth service.
func (c *Client) MultiFactorAuth() *MultiFactorAuthService {
	return c.multiFactorAuth
}

// Connect returns the Connect service.
func (c *Client) Connect() *ConnectService {
	return c.connect
}

// Authorization returns the Authorization service.
func (c *Client) Authorization() *AuthorizationService {
	return c.authorization
}

// SSO returns the SSO service.
func (c *Client) SSO() *SSOService {
	return c.sso
}

// Pipes returns the Pipes service.
func (c *Client) Pipes() *PipeService {
	return c.pipes
}

// DirectorySync returns the DirectorySync service.
func (c *Client) DirectorySync() *DirectorySyncService {
	return c.directorySync
}

// Events returns the Events service.
func (c *Client) Events() *EventService {
	return c.events
}

// FeatureFlags returns the FeatureFlags service.
func (c *Client) FeatureFlags() *FeatureFlagService {
	return c.featureFlags
}

// OrganizationDomains returns the OrganizationDomains service.
func (c *Client) OrganizationDomains() *OrganizationDomainService {
	return c.organizationDomains
}

// Organizations returns the Organizations service.
func (c *Client) Organizations() *OrganizationService {
	return c.organizations
}

// AdminPortal returns the AdminPortal service.
func (c *Client) AdminPortal() *AdminPortalService {
	return c.adminPortal
}

// Radar returns the Radar service.
func (c *Client) Radar() *RadarService {
	return c.radar
}

// UserManagement returns the UserManagement service.
func (c *Client) UserManagement() *UserManagementService {
	return c.userManagement
}

// Webhooks returns the Webhooks service.
func (c *Client) Webhooks() *WebhookService {
	return c.webhooks
}

// Widgets returns the Widgets service.
func (c *Client) Widgets() *WidgetService {
	return c.widgets
}

// AuditLogs returns the AuditLogs service.
func (c *Client) AuditLogs() *AuditLogService {
	return c.auditLogs
}
