name: CI

on:
  push:
    branches:
      - 'main'
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 'stable'
          - 'oldstable'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # 6.5.0
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: |
          go mod download
          go build ./...

      - name: Run Tests
        run: |
          go test -v ./...
